### ISSUE TITLE
AssertionError: Neuron compile failed.  Operator aten::leaky_relu_ is not supported

### ISSUE THREAD

**Issue by williamdias** [aws/aws-neuron-sdk#129]
Hi,

I am trying to compile a pytorch model to AWS Neuron, but I am facing the following error:
```
Traceback (most recent call last):
  File "test_detector_pytorch.py", line 26, in <module>
    face_detector.save_neuron()
  File "/home/ubuntu/facerec/src/app/face_detector_pytorch.py", line 31, in save_neuron
    model_neuron = torch.neuron.trace(self.net, example_inputs=[image])
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 71, in trace
    transform_torch_graph_to_tensorflow( func, example_inputs, *args, **kwargs )
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 291, in transform_torch_graph_to_tensorflow
    tensor_outputs = _resolve_func(node)(op, *tensor_inputs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 1082, in _resolve_func
    assert hasattr(module, func_name), "Neuron compile failed.  Operator {}::{} is not supported".format(mod_name,func_name)
AssertionError: Neuron compile failed.  Operator aten::leaky_relu_ is not supported
```
Is it a bug or AWS Neuron does not support LeakyReLU yet? 
Another question: is it possible for my model to have a variable input size? I want to perform face detection on images of different sizes, but the documentation says CNN models have an input size limit of 480x480. Is there any alternative?

Thanks!

**Comment by aws-renfu** [comment]
Hi William,

Please consult [link](https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md) for the list of supported operators. You are correct that we do not support LeakyReLU yet in the current release.

To support variable input sizes for face detection, it is best to compile the neural network for each input size. Please stay tuned for the upcoming releases where we lift the restriction on input sizes.

Thanks,

--Randy

**Comment by williamdias** [comment]
Thanks for the reply!
