### ISSUE TITLE
Operator aten::ne is not supported

### ISSUE THREAD

**Issue by djstrong** [aws/aws-neuron-sdk#135]
I have tried compilation of roberta-base model (`RobertaForSequenceClassification`) and got:
```
AssertionError: Neuron compile failed.  Operator aten::ne is not supported
```
`BERTForSequenceClassification` (from https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb) should have the same architecture.

**Comment by djstrong** [comment]
I have tried to do https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb:
```
$ python3 -m pip install torch-neuron neuron-cc[tensorflow] transformers --upgrade --extra-index-url=https://pip.repos.neuron.amazonaws.com
...
ERROR: torchvision 0.4.2 requires torch==1.3.1, which is not installed.
ERROR: tensorflow-neuron 1.15.2.1.0.1796.0 requires tensorboard-neuron<1.16.0,>=1.15.0, which is not installed.
...
Successfully installed dmlc-nnvm-1.0.2732.0+6020726378 dmlc-topi-1.0.2732.0+6020726378 dmlc-tvm-1.0.2732.0+6020726378 inferentia-hwm-1.0.1516.0+6020726378 markdown-3.2.2 neuron-cc-1.0.16861.0+6021080341 numpy-1.18.2 tensorboard-1.15.0 tensorflow-1.15.0 torch-neuron-1.0.1386.0
```
```
$ python3 test_temp.py
Traceback (most recent call last):
  File "test_temp.py", line 4, in <module>
    import torch.neuron
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/neuron/__init__.py", line 1, in <module>
    from torch_neuron import *
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/__init__.py", line 7, in <module>
    from .convert import trace
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 7, in <module>
    from torch_neuron import graph
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py", line 4, in <module>
    from torch_neuron.resolve_function import get_function
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/resolve_function.py", line 7, in <module>
    from torch_neuron import tensor_info
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/tensor_info.py", line 84, in <module>
    3: torch.channels_last_3d,
AttributeError: module 'torch' has no attribute 'channels_last_3d'
```

**Comment by aws-diamant** [comment]
Hi djstrong,

Thanks for posting this question!
Were you able to successfully complete the unmodified tutorial?
If yes, could you please share the modified code with us, so that we will investigate the error?

Thanks,
Ron

**Comment by aws-diamant** [comment]
FYI, I did try to modify the tutorial locally to use roberta-base, and it seems to compile successfully for me (however I'm not sure that this matches what you did).

The changes I’ve made to the code in the tutorial are listed below:
```
- from transformers import AutoTokenizer, AutoModelForSequenceClassification
+ from transformers import AutoTokenizer, RobertaForSequenceClassification

- model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased-finetuned-mrpc")
+ model = RobertaForSequenceClassification.from_pretrained("bert-base-cased-finetuned-mrpc”)
```

Thanks,
Ron

**Comment by djstrong** [comment]
Thank you.

I haven't successfully run the tutorial yet.

The only change needed to test Roberta model is to change `bert-base-cased-finetuned-mrpc` to e.g. `textattack/roberta-base-MRPC` (in `AutoTokenizer` and `AutoModelForSequenceClassification`).

**Comment by aws-diamant** [comment]
Thanks for sharing the info, djstrong.

I was able to repeat your experiment and compile the model successfully, so I estimate that this issue will be resolved once you're able to get the original tutorial to work (hopefully by updating the torch-neuron package).

Just as FYI, I noticed slight differences between the Roberta and BERT tokenizers. The code that worked for me is given below: 
```python
# You may save the content of this cell as compile_bert.py and run it with python3.
import tensorflow  # to workaround a protobuf version conflict issue
import torch
import torch.neuron
from transformers import AutoTokenizer, AutoModelForSequenceClassification


# Build tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("textattack/roberta-base-MRPC")
model = AutoModelForSequenceClassification.from_pretrained("textattack/roberta-base-MRPC")

# Setup some example inputs
sequence_0 = "The company HuggingFace is based in New York City"
sequence_1 = "Apples are especially bad for your health"
sequence_2 = "HuggingFace's headquarters are situated in Manhattan"
paraphrase = tokenizer.encode_plus(sequence_0, sequence_2, max_length=128, pad_to_max_length=True, return_tensors="pt")
not_paraphrase = tokenizer.encode_plus(sequence_0, sequence_1, max_length=128, pad_to_max_length=True, return_tensors="pt")

# Run the original PyTorch model on both example inputs
paraphrase_classification_logits = model(**paraphrase)[0]
not_paraphrase_classification_logits = model(**not_paraphrase)[0]

# Convert example inputs to a format that is compatible with TorchScript tracing
example_inputs_paraphrase = paraphrase['input_ids'], paraphrase['attention_mask']
example_inputs_not_paraphrase = not_paraphrase['input_ids'], not_paraphrase['attention_mask']

# Run torch.neuron.trace to generate a TorchScript that is optimized by AWS Neuron, using optimization level -O2
model_neuron = torch.neuron.trace(model, example_inputs_paraphrase, compiler_args=['-O2'])

# Verify the TorchScript works on both example inputs
paraphrase_classification_logits_neuron = model_neuron(*example_inputs_paraphrase)
not_paraphrase_classification_logits_neuron = model_neuron(*example_inputs_not_paraphrase)

# Save the TorchScript for later use
model_neuron.save('bert_neuron.pt')
```

**Comment by djstrong** [comment]
Thank you, this is great information.

**Comment by djstrong** [comment]
Thank you, the Roberta model compiled the same as BERT.
