### ISSUE TITLE
Torch LSTM encoder error: TypeError: forward() missing 1 required positional argument: 'src_lengths'

### ISSUE THREAD

**Issue by loretoparisi** [aws/aws-neuron-sdk#207]
Hi, my torch `nnModule` uses a `nn.LSTM` as text embedding encoder.
When calling

```python
torch.neuron.analyze_model(model, example_inputs = example_inputs )
````

I get a 

```
Traceback (most recent call last):
  File "compile_torch.py", line 58, in <module>
    torch.neuron.analyze_model( laser_encoder.model(), example_inputs = example_inputs )
  File "/usr/local/lib/python3.7/site-packages/torch_neuron/model_support.py", line 203, in analyze_model
    neuron_graph = convert.to_graph(model, example_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch_neuron/convert.py", line 186, in to_graph
    jit_trace = torch.jit.trace(func_or_mod, example_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 875, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 1027, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'src_lengths'
```

due to the signature of the `forward` of the encoder:

```python
   def forward(self, src_tokens, src_lengths):
        """
        Args:
            src_tokens (LongTensor): tokens in the source language of shape
                `(batch, src_len)`
            src_lengths (LongTensor): lengths of each source sentence of shape
                `(batch)`
        """
        if self.left_pad:
            # convert left-padding to right-padding
            src_tokens = convert_padding_direction(
                src_tokens,
                self.padding_idx,
                left_to_right=True,
            )

        bsz, seqlen = src_tokens.size()

        # embed tokens
        x = self.embed_tokens(src_tokens)

        # B x T x C -> T x B x C
        x = x.transpose(0, 1)

        # pack embedded source tokens into a PackedSequence
        packed_x = nn.utils.rnn.pack_padded_sequence(x, src_lengths.data.tolist())

        # apply LSTM
        if self.bidirectional:
            state_size = 2 * self.num_layers, bsz, self.hidden_size
        else:
            state_size = self.num_layers, bsz, self.hidden_size
        h0 = x.data.new(*state_size).zero_()
        c0 = x.data.new(*state_size).zero_()
        packed_outs, (final_hiddens, final_cells) = self.lstm(packed_x, (h0, c0))

        # unpack outputs and apply dropout
        x, _ = nn.utils.rnn.pad_packed_sequence(packed_outs, padding_value=self.padding_value)
        assert list(x.size()) == [seqlen, bsz, self.output_units]

        if self.bidirectional:

            def combine_bidir(outs):
                return torch.cat([
                    torch.cat([outs[2 * i], outs[2 * i + 1]], dim=0).view(1, bsz, self.output_units)
                    for i in range(self.num_layers)
                ], dim=0)

            final_hiddens = combine_bidir(final_hiddens)
            final_cells = combine_bidir(final_cells)

        encoder_padding_mask = src_tokens.eq(self.padding_idx).t()

        # Set padded outputs to -inf so they are not selected by max-pooling
        padding_mask = src_tokens.eq(self.padding_idx).t().unsqueeze(-1)
        if padding_mask.any():
            x = x.float().masked_fill_(padding_mask, float('-inf')).type_as(x)

        # Build the sentence embedding by max-pooling over the encoder outputs
        sentemb = x.max(dim=0)[0]

        return {
            'sentemb': sentemb,
            'encoder_out': (x, final_hiddens, final_cells),
            'encoder_padding_mask': encoder_padding_mask if encoder_padding_mask.any() else None
        }
```

and the init

```python
super().__init__()

        self.num_layers = num_layers
        self.bidirectional = bidirectional
        self.hidden_size = hidden_size

        self.padding_idx = padding_idx
        self.embed_tokens = nn.Embedding(num_embeddings, embed_dim, padding_idx=self.padding_idx)

        self.lstm = nn.LSTM(
            input_size=embed_dim,
            hidden_size=hidden_size,
            num_layers=num_layers,
            bidirectional=bidirectional,
        )
        self.left_pad = left_pad
        self.padding_value = padding_value

        self.output_units = hidden_size
        if bidirectional:
            self.output_units *= 2
```

**Comment by aws-renfu** [comment]
Thanks for bringing this issue to our attention. We will take a look and suggest a work-around.

**Comment by mrnikwaws** [comment]
Here is some sample code roughly equivalent to what you provided for analyzing the model.  Note the array of example_inputs

However the core operator (aten::lstm) is not currently supported:

```
import torch
import torch.neuron

class NeuronLSTM(torch.nn.Module):

    def __init__(
            self,
            num_layers=3,
            num_embeddings=32,
            bidirectional=True,
            hidden_size=128,
            padding_idx=0,
            padding_value=0,
            embed_dim=32,
            left_pad=1):
        super().__init__()

        #self.src_lengths = src_lengths

        self.num_layers = num_layers
        self.bidirectional = bidirectional
        self.hidden_size = hidden_size

        self.padding_idx = padding_idx
        self.embed_tokens = torch.nn.Embedding(
            num_embeddings, embed_dim, padding_idx=self.padding_idx)

        self.lstm = torch.nn.LSTM(
            input_size=embed_dim,
            hidden_size=hidden_size,
            num_layers=num_layers,
            bidirectional=bidirectional,
        )
        self.left_pad = left_pad
        self.padding_value = padding_value

        self.output_units = hidden_size
        if bidirectional:
            self.output_units *= 2

    def forward(self, src_tokens, src_lengths):
        """
        Args:
            src_tokens (LongTensor): tokens in the source language of shape
                `(batch, src_len)`
            src_lengths (LongTensor): lengths of each source sentence of shape
                `(batch)`
        """
        # if self.left_pad:
        # convert left-padding to right-padding
        # src_tokens = convert_padding_direction(
        #    src_tokens,
        #    self.padding_idx,
        #    left_to_right=True,
        # )

        bsz, seqlen = src_tokens.size()

        # embed tokens
        x = self.embed_tokens(src_tokens)

        # B x T x C -> T x B x C
        x = x.transpose(0, 1)

        # pack embedded source tokens into a PackedSequence
        packed_x = torch.nn.utils.rnn.pack_padded_sequence(
            x, src_lengths.data.tolist())

        # apply LSTM
        if self.bidirectional:
            state_size = 2 * self.num_layers, bsz, self.hidden_size
        else:
            state_size = self.num_layers, bsz, self.hidden_size
        h0 = x.data.new(*state_size).zero_()
        c0 = x.data.new(*state_size).zero_()
        packed_outs, (final_hiddens, final_cells) = self.lstm(
            packed_x, (h0, c0))

        # unpack outputs and apply dropout
        x, _ = torch.nn.utils.rnn.pad_packed_sequence(
            packed_outs, padding_value=self.padding_value)
        assert list(x.size()) == [seqlen, bsz, self.output_units]

        if self.bidirectional:

            def combine_bidir(outs):
                return torch.cat([
                    torch.cat([outs[2 * i], outs[2 * i + 1]],
                              dim=0).view(1, bsz, self.output_units)
                    for i in range(self.num_layers)
                ], dim=0)

            final_hiddens = combine_bidir(final_hiddens)
            final_cells = combine_bidir(final_cells)

        encoder_padding_mask = src_tokens.eq(self.padding_idx).t()

        # Set padded outputs to -inf so they are not selected by max-pooling
        padding_mask = src_tokens.eq(self.padding_idx).t().unsqueeze(-1)
        if padding_mask.any():
            x = x.float().masked_fill_(padding_mask, float('-inf')).type_as(x)

        # Build the sentence embedding by max-pooling over the encoder outputs
        sentemb = x.max(dim=0)[0]

        output = [sentemb, x, final_hiddens, final_cells]

        if encoder_padding_mask.any():
            output.append(encoder_padding_mask)

        # return {
        #    'sentemb': sentemb,
        #    'encoder_out': (x, final_hiddens, final_cells),
        #    'encoder_padding_mask': encoder_padding_mask if encoder_padding_mask.any() else None
        # }

        return output

length = 160

src_lengths = torch.tensor(
    [160, 140, 120, 100, 80, 60, 40, 20], dtype=torch.long)
src_tokens = torch.ones(len(src_lengths), length, dtype=torch.long)


model = NeuronLSTM()

example_inputs = [src_tokens, src_lengths]
results = torch.neuron.analyze_model(model, example_inputs=example_inputs)

print(results)
```
Note the output that I see:
```
INFO:Neuron:The following operations are currently supported in torch-neuron for this model:
INFO:Neuron:aten::max
INFO:Neuron:aten::size
INFO:Neuron:prim::ListConstruct
INFO:Neuron:aten::empty
INFO:Neuron:prim::TupleConstruct
INFO:Neuron:aten::cat
INFO:Neuron:aten::transpose
INFO:Neuron:prim::NumToTensor
INFO:Neuron:aten::Int
INFO:Neuron:aten::view
INFO:Neuron:prim::TupleUnpack
INFO:Neuron:aten::to
INFO:Neuron:prim::Constant
INFO:Neuron:aten::select
INFO:Neuron:The following operations are currently not supported in torch-neuron for this model:
INFO:Neuron:aten::_pack_padded_sequence
INFO:Neuron:aten::_pad_packed_sequence
INFO:Neuron:aten::embedding
INFO:Neuron:aten::lstm
INFO:Neuron:aten::zero_
INFO:Neuron:96.61% of all operations (including primitives) (171 of 177) are supported
INFO:Neuron:86.96% of arithmetic operations (40 of 46) are supported
OrderedDict([('percent_supported', 96.61016949152543), ('percent_supported_arithmetic', 86.95652173913044), ('supported_count', 171), ('total_count', 177), ('supported_count_arithmetic', 40), ('total_count_arithmetic', 46), ('supported_operators', {'aten::max', 'aten::size', 'prim::ListConstruct', 'aten::empty', 'prim::TupleConstruct', 'aten::cat', 'aten::transpose', 'prim::NumToTensor', 'aten::Int', 'aten::view', 'prim::TupleUnpack', 'aten::to', 'prim::Constant', 'aten::select'}), ('unsupported_operators', ['aten::_pack_padded_sequence', 'aten::_pad_packed_sequence', 'aten::embedding', 'aten::lstm', 'aten::zero_']), ('operators', ['aten::Int', 'aten::_pack_padded_sequence', 'aten::_pad_packed_sequence', 'aten::cat', 'aten::embedding', 'aten::empty', 'aten::lstm', 'aten::max', 'aten::select', 'aten::size', 'aten::to', 'aten::transpose', 'aten::view', 'aten::zero_', 'prim::Constant', 'prim::ListConstruct', 'prim::NumToTensor', 'prim::TupleConstruct', 'prim::TupleUnpack']), ('operator_count', OrderedDict([('aten::Int', 7), ('aten::_pack_padded_sequence', 1), ('aten::_pad_packed_sequence', 1), ('aten::cat', 8), ('aten::embedding', 1), ('aten::empty', 2), ('aten::lstm', 1), ('aten::max', 1), ('aten::select', 12), ('aten::size', 2), ('aten::to', 1), ('aten::transpose', 1), ('aten::view', 6), ('aten::zero_', 2), ('prim::Constant', 108), ('prim::ListConstruct', 19), ('prim::NumToTensor', 2), ('prim::TupleConstruct', 1), ('prim::TupleUnpack', 1)]))])
```

**Comment by loretoparisi** [comment]
@mrnikwaws thanks for the `example_inputs`, and the code snippet (I have tried it and I get the same output as yours), now it's more clear. That said, I'm not sure I can adapt your code to mine. In any case it seems it would not work because most of the operations seems to be not supported right now. @aws-renfu Is this correct? My code is a slightly adaptation of [this one](https://github.com/facebookresearch/LASER/blob/master/source/embed.py), if you want to make further tests on this LSTM.

**Comment by aws-taylor** [comment]
Hello  loretoparisi,
  
  We have been able to reproduce the error you were originally seeing and are working towards a fix. We will continue to update this ticket as we make more progress. Moreover, we are working to add support for the `aten::lstm` operator so that you can get better performance on this model. I encourage you to watch our [release notes](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/README.html) for information on new operator support.

Regards,
Taylor

**Comment by loretoparisi** [comment]
@aws-taylor thank you very much fo the update!

**Comment by AWSGH** [comment]
we converted this issue to a roadmap item the team is working on. Thanks for reporting it to us, and please monitor our releases and roadmap to be notified the error and aten::lstm support will be added. I will go ahead and close this ticket for now.
