### ISSUE TITLE
'Evaluate YOLO v4 on Inferentia' tutorial does not compile

### ISSUE THREAD

**Issue by gytdau** [aws/aws-neuron-sdk#239]
The 'Evaluate YOLO v4 on Inferentia' tutorial found [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/yolo_v4_tutorial/compile_evaluate.html) does not compile. On the step:

```
def subgraph_builder_function(node):
    return 'YoloLayer' not in node.name

model_neuron = torch.neuron.trace(model, image, subgraph_builder_function=subgraph_builder_function)
model_neuron.save('yolo_v4_neuron.pt')
```
the following output is given:
```
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/numpy/core/function_base.py:113: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  num = operator.index(num)
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel_launcher.py:528: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/ipykernel_launcher.py:530: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
INFO:Neuron:There are 123 ops of 2 different types in the TorchScript that are not compiled by neuron-cc: aten::slice, aten::size, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 1114, fused = 572, percent fused = 51.35%
INFO:Neuron:compiling function _NeuronGraph$4108 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpv4wf5i2j/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpv4wf5i2j/graph_def.neff --io-config {"inputs": {"0:0": [[1, 3, 608, 608], "float32"]}, "outputs": ["transpose_473:0", "transpose_511:0", "transpose_549:0"]} --verbose 0'
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on <GraphOperation _NeuronGraph#0>; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpv4wf5i2j/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpv4wf5i2j/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 608, 608], "float32"]}, "outputs": ["transpose_473:0", "transpose_511:0", "transpose_549:0"]}' --verbose 0
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 502, in _convert_item
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 182, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpv4wf5i2j/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpv4wf5i2j/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 608, 608], "float32"]}, "outputs": ["transpose_473:0", "transpose_511:0", "transpose_549:0"]}' --verbose 0
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 1114, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 82 [supported]
INFO:Neuron: => aten::_convolution: 110 [supported]
INFO:Neuron: => aten::add: 47 [supported]
INFO:Neuron: => aten::batch_norm: 107 [supported]
INFO:Neuron: => aten::cat: 45 [supported]
INFO:Neuron: => aten::contiguous: 2 [supported]
INFO:Neuron: => aten::detach: 18 [supported]
INFO:Neuron: => aten::div: 6 [supported]
INFO:Neuron: => aten::exp: 3 [supported]
INFO:Neuron: => aten::expand: 2 [supported]
INFO:Neuron: => aten::floor_divide: 4 [supported]
INFO:Neuron: => aten::leaky_relu: 35 [supported]
INFO:Neuron: => aten::max_pool2d: 3 [supported]
INFO:Neuron: => aten::mul: 153 [supported]
INFO:Neuron: => aten::permute: 3 [supported]
INFO:Neuron: => aten::reshape: 3 [supported]
INFO:Neuron: => aten::sigmoid: 9 [supported]
INFO:Neuron: => aten::size: 115 [supported]
INFO:Neuron: => aten::slice: 168 [supported]
INFO:Neuron: => aten::softplus: 72 [supported]
INFO:Neuron: => aten::sub: 9 [supported]
INFO:Neuron: => aten::tanh: 72 [supported]
INFO:Neuron: => aten::to: 18 [supported]
INFO:Neuron: => aten::view: 28 [supported]
```
raising an exception:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-86314bdca631> in <module>()
      2     return 'YoloLayer' not in node.name
      3 
----> 4 model_neuron = torch.neuron.trace(model, image, subgraph_builder_function=subgraph_builder_function)
      5 model_neuron.save('yolo_v4_neuron.pt')

/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, **kwargs)
    168     if succesful_compilations == 0 and not allow_no_ops_on_neuron:
    169         raise RuntimeError(
--> 170             "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    171 
    172     if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```
This is running on a c5.4xlarge instance on EC2.

**Comment by gytdau** [comment]
Nevermind! ;)

This was solved by, of course, installing the actual requirements:
```
pip install neuron-cc[tensorflow]
pip install torch-neuron
```
