### ISSUE TITLE
[bentoML service on inf1] RuntimeError: forward() is missing value for argument 'tensor'.

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [aws/aws-neuron-sdk#274]
Hello,

I tried to save a bentoML service of a roBERTa model on inf1 instance with this code:

```
from typing import List
from bentoml import env, artifacts, api, BentoService
from bentoml.adapters import JsonInput
from bentoml.frameworks.pytorch import PytorchModelArtifact
from bentoml.service.artifacts.common import PickleArtifact
import torch
import torch_neuron
import os

# one core per worker
os.environ['NEURONCORE_GROUP_SIZES'] = '1'

@env(requirements_txt_file='./requirements.txt',
    docker_base_image="bentoml/model-server:0.12.0-slim-py36")
@artifacts([PytorchModelArtifact('model'), PickleArtifact('tokenizer')])
class StsBTCustomInf1PytorchService(BentoService):
    @api(input=JsonInput(), batch=True)
    def predict(self, list_sentences: List[str]):
        tokenizer = self.artifacts.tokenizer
        encoded_input = tokenizer(list_sentences, padding='max_length', truncation=True, max_length=128, return_tensors='pt')
        with torch.no_grad():
            #Compute token embeddings
            model_output = self.artifacts.model(**encoded_input)
        return model_output.numpy()

## Import the PytorchStsTransformerCpuService class defined
from transformers import AutoTokenizer

sts_pt = StsBTCustomInf1PytorchService()

# Pack a TorchScript Model
model = torch.jit.load('stsb-xlm-r-multilingual-custom-neuron-data-parallel-pad128-b1.pt')
model.eval()
sts_pt.pack('model', model)

tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/stsb-xlm-r-multilingual", use_fast=True)
sts_pt.pack('tokenizer', tokenizer)

# Save BentoService
sts_pt.save()
```
However, when trying to start the bentoML service in inf1 instance with: `bentoml serve-gunicorn --enable-microbatch $saved_path --workers 1 --port=5000`

An trying to test API inference with the following code:

```
import requests
import json
import numpy as np
import torch

API_url = "http://ec2-xx-xx-xx-xx.eu-west-3.compute.amazonaws.com:5000/predict"
sentences1 = ["Navigateur Web : Ce logiciel permet d'accéder à des pages web depuis votre ordinateur. Il en existe plusieurs téléchargeables gratuitement comme Google Chrome ou Mozilla. Certains sont même déjà installés comme Safari sur Mac OS et Edge sur Microsoft."]
response1 = requests.post(API_url, json=sentences1[0])
```

I got the following error log:
```
[2021-06-04 09:01:18,711] INFO - Starting BentoML proxy in production mode..
[2021-06-04 09:01:18,712] INFO - Starting BentoML API server in production mode..
[2021-06-04 09:01:18,880] INFO - Running micro batch service on :5000
[2021-06-04 09:01:18 +0000] [1998] [INFO] Starting gunicorn 20.1.0
[2021-06-04 09:01:18 +0000] [1998] [INFO] Listening at: http://0.0.0.0:5000 (1998)
[2021-06-04 09:01:18 +0000] [1998] [INFO] Using worker: aiohttp.worker.GunicornWebWorker
[2021-06-04 09:01:18 +0000] [2005] [INFO] Starting gunicorn 20.1.0
[2021-06-04 09:01:18 +0000] [2005] [INFO] Listening at: http://0.0.0.0:48079 (2005)
[2021-06-04 09:01:18 +0000] [2005] [INFO] Using worker: sync
[2021-06-04 09:01:18 +0000] [2006] [INFO] Booting worker with pid: 2006
[2021-06-04 09:01:18 +0000] [2007] [INFO] Booting worker with pid: 2007
[2021-06-04 09:01:18,910] INFO - Micro batch enabled for API `predict` max-latency: 20000 max-batch-size 4000
[2021-06-04 09:01:18,910] INFO - Your system nofile limit is 8192, which means each instance of microbatch service is able to hold this number of connections at same time. You can increase the number of file descriptors for the server process, or launch more microbatch instances to accept more concurrent connection.
[2021-06-04 09:01:19,788] INFO - Using user specified docker base image: `bentoml/model-server:0.12.0-slim-py36`, usermust make sure that the base image either has Python 3.6 or conda installed.
[2021-06-04 09:01:20,818] WARNING - BentoML by default does not include spacy and torchvision package when using PytorchModelArtifact. To make sure BentoML bundle those packages if they are required for your model, either import those packages in BentoService definition file or manually add them via `@env(pip_packages=['torchvision'])` when defining a BentoService
[2021-06-04 09:04:08,791] ERROR - Error caught in API function:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/test_bentoml_inf1_fresh/lib/python3.6/site-packages/bentoml/service/inference_api.py", line 177, in wrapped_func
    return self._user_func(*args, **kwargs)
  File "/home/ubuntu/bentoml/repository/StsBTCustomInf1PytorchService/20210604083513_74AEBF/StsBTCustomInf1PytorchService/sts_transformer_pt_inf1_batchTrue_custom_requirement_file.py", line 33, in predict
    model_output = self.artifacts.model(**encoded_input)
  File "/home/ubuntu/anaconda3/envs/test_bentoml_inf1_fresh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: forward() is missing value for argument 'tensor'. Declaration: forward(__torch__.torch_neuron.convert.AwsNeuronGraphModule self, Tensor tensor, Tensor tensor0) -> (Tensor)
```

Could anyone help me regarding this problem?

**Comment by awsilya** [comment]
hi Matthieu, since you opened #275 it would appear that you've overcame this problem.  Could we close it?

**Comment by Matthieu-Tinycoaching** [comment]
Hi @awsilya  yes I overcome this problem by using keyword arguments.
