### ISSUE TITLE
Internal Compiler Error: sentence-transformer with neuroncore_pipeline_cores = 4 and batch = 10

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [aws/aws-neuron-sdk#280]
```
Libraries versions:
neuron-cc == 1.3.7.0
torch-neuron == 1.7.1.1.3.5.0
```

Hello,

I tried to compile a sentence-transformer model with `neuroncore_pipeline_cores = 4` and `batch = 10` according the following code:

```
import tensorflow  # to workaround a protobuf version conflict issue
import torch
import torch.neuron
import transformers

#### I/ Compile the sts-transformer with torchscript ####

model_name = "sentence-transformers/stsb-xlm-r-multilingual"
pipeline_name = "feature-extraction"
nlp = transformers.pipeline(pipeline_name, model=model_name, tokenizer=model_name, device=-1)
tokenizer = nlp.tokenizer

class SentenceTransformerCustom(transformers.XLMRobertaModel):
    def __init__(self, config):
        super().__init__(config)
        # Naming alias for ONNX output specification
        # Makes it easier to identify the layer
        self.sentence_embedding = torch.nn.Identity()

    def forward(self, input_ids, attention_mask):
        # Get the token embeddings from the base model
        token_embeddings = super().forward(
            input_ids, 
            attention_mask=attention_mask
        )[0]
        # Stack the pooling layer on top of it
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
        sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)
        return self.sentence_embedding(sum_embeddings / sum_mask)

model = SentenceTransformerCustom(config=nlp.model.config).from_pretrained(model_name, return_dict=False)

src_text = "Adresse électronique : Pour pouvoir s'échanger des messages électroniques il faut une adresse... électronique ! Tout comme avoir une adresse postale est mieux pour recevoir une lettre. L'adresse électronique peut être obtenue auprès d'un fournisseur de messagerie (Gmail, Hotmail, etc.), et se découpe en 3 parties : l'identifiant que vous avez choisi (ex. : bobforever), l'arobase (@), et le nom de domaine (ex. : gmail.com)."

max_length=128
dummy_phrase = tokenizer(src_text, padding='max_length', truncation=True, max_length=max_length, return_tensors='pt')

batch_size = 10
example_inputs_dummy_phrase = (
    torch.cat([dummy_phrase['input_ids']] * batch_size,0),
    torch.cat([dummy_phrase['attention_mask']] * batch_size,0)
)

neuroncore_pipeline_cores = 4 # This string should be '4' on an inf1.xlarge
neuron_pipeline_model = torch.neuron.trace(model,
                                        example_inputs = example_inputs_dummy_phrase,
                                        verbose=1,
                                        compiler_args = ['--neuroncore-pipeline-cores', str(neuroncore_pipeline_cores)],
                                        compiler_workdir='./'
                                        )
neuron_pipeline_model.save("stsb-xlm-r-multilingual-custom-neuron-pipeline{}-parallel-pad128-b{}.pt".format(neuroncore_pipeline_cores, batch_size))
```
but got the following error log:

```
Marking MatMul in-edges used as weights
SG-ERROR: File /opt/brazil-pkg-cache/packages/KaenaCompiler/KaenaCompiler-1.3.7.0/AL2012/generic-flavor/src/neuroncc/compiler/be/tongacodegen/src/tongacodegentensortensor.cpp:207, Assertion 'deltaElems <= max' failed: After TensorTensor to TensorReduce transformation for op I-11977-6158 the new step is too large: Step=46208 > Max=32767
06/16/2021 10:18:12 AM ERROR [neuron-cc]: ***************************************************************
06/16/2021 10:18:12 AM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
06/16/2021 10:18:12 AM ERROR [neuron-cc]: ***************************************************************
06/16/2021 10:18:12 AM ERROR [neuron-cc]: 
06/16/2021 10:18:12 AM ERROR [neuron-cc]: Error message:  Non-zero exit status (1) for command: /home/matthieu/neuron_stable_venv/lib/python3.6/site-packages/neuroncc/starfish/bin/stargazer.exe  --bir backend.bir --tensor_map tensor_map.json  --logfile /home/matthieu/Code/88/log-neuron-cc.txt --verbose 20 --act-root-json /home/matthieu/neuron_stable_venv/lib/python3.6/site-packages/neuroncc/pwp/pwp_bin_with_ln/act_info.json
06/16/2021 10:18:12 AM ERROR [neuron-cc]: 
06/16/2021 10:18:12 AM ERROR [neuron-cc]: Error class:    CompilerInternalError
06/16/2021 10:18:12 AM ERROR [neuron-cc]: Error location: job.Backend.3
06/16/2021 10:18:12 AM ERROR [neuron-cc]: Command line:   /home/matthieu/neuron_stable_venv/bin/neuron-cc compile /home/matthieu/Code/88/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/matthieu/Code/88/graph_def.neff --io-config '{"inputs": {"0:0": [[10, 128, 768], "float32"], "1:0": [[10, 1, 1, 128], "float32"], "2:0": [[10, 128], "int64"]}, "outputs": ["truediv_12:0"]}' --neuroncore-pipeline-cores 4 --verbose 1
06/16/2021 10:18:12 AM ERROR [neuron-cc]: 
06/16/2021 10:18:12 AM ERROR [neuron-cc]: Internal details:
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 242, in neuroncc.driver.Job.runSingleInputFn
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Backend.py", line 96, in neuroncc.driver.jobs.Backend.Backend.runSingleInput
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 176, in neuroncc.driver.Job.Job.shellCommand
06/16/2021 10:18:12 AM ERROR [neuron-cc]: 
06/16/2021 10:18:12 AM ERROR [neuron-cc]: Version information:
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   Neuron Compiler version 1.3.7.0+fc8e67ab4
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   HWM version 1.3.1.0-0
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   NEFF version 1.0
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   TVM version 1.3.1.0+0
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   NumPy version 1.19.5
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   MXNet not available
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   TF not available
06/16/2021 10:18:12 AM ERROR [neuron-cc]:   ONNX not available
06/16/2021 10:18:12 AM ERROR [neuron-cc]: 
06/16/2021 10:18:12 AM ERROR [neuron-cc]: Artifacts stored in: /home/matthieu/Code/88
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$655; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/matthieu/neuron_stable_venv/bin/neuron-cc compile /home/matthieu/Code/88/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/matthieu/Code/88/graph_def.neff --io-config '{"inputs": {"0:0": [[10, 128, 768], "float32"], "1:0": [[10, 1, 1, 128], "float32"], "2:0": [[10, 128], "int64"]}, "outputs": ["truediv_12:0"]}' --neuroncore-pipeline-cores 4 --verbose 1
Traceback (most recent call last):
  File "/home/matthieu/neuron_stable_venv/lib/python3.6/site-packages/torch_neuron/convert.py", line 313, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/matthieu/neuron_stable_venv/lib/python3.6/site-packages/torch_neuron/decorators.py", line 191, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/matthieu/neuron_stable_venv/bin/neuron-cc compile /home/matthieu/Code/88/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/matthieu/Code/88/graph_def.neff --io-config '{"inputs": {"0:0": [[10, 128, 768], "float32"], "1:0": [[10, 1, 1, 128], "float32"], "2:0": [[10, 128], "int64"]}, "outputs": ["truediv_12:0"]}' --neuroncore-pipeline-cores 4 --verbose 1
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 730, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 101 [supported]
INFO:Neuron: => aten::add: 112 [supported]
INFO:Neuron: => aten::addmm: 1 [supported]
INFO:Neuron: => aten::clamp: 1 [supported]
INFO:Neuron: => aten::contiguous: 12 [supported]
INFO:Neuron: => aten::cumsum: 1 [not supported]
INFO:Neuron: => aten::div: 13 [supported]
INFO:Neuron: => aten::dropout: 37 [supported]
INFO:Neuron: => aten::embedding: 3 [not supported]
INFO:Neuron: => aten::expand: 1 [supported]
INFO:Neuron: => aten::gelu: 12 [supported]
INFO:Neuron: => aten::layer_norm: 25 [supported]
INFO:Neuron: => aten::matmul: 96 [supported]
INFO:Neuron: => aten::mul: 3 [supported]
INFO:Neuron: => aten::ne: 1 [supported]
INFO:Neuron: => aten::permute: 48 [supported]
INFO:Neuron: => aten::rsub: 1 [supported]
INFO:Neuron: => aten::select: 1 [supported]
INFO:Neuron: => aten::size: 101 [supported]
INFO:Neuron: => aten::slice: 3 [supported]
INFO:Neuron: => aten::softmax: 12 [supported]
INFO:Neuron: => aten::sum: 2 [supported]
INFO:Neuron: => aten::t: 73 [supported]
INFO:Neuron: => aten::to: 5 [supported]
INFO:Neuron: => aten::transpose: 12 [supported]
INFO:Neuron: => aten::type_as: 1 [not supported]
INFO:Neuron: => aten::unsqueeze: 3 [supported]
INFO:Neuron: => aten::view: 48 [supported]
INFO:Neuron: => aten::zeros: 1 [supported]
Traceback (most recent call last):
  File "/home/matthieu/Code/Python/torchserve_sts_transformer_torchscript_cpu_pad128_pipeline4_b10.py", line 93, in <module>
    compiler_workdir='./'
  File "/home/matthieu/neuron_stable_venv/lib/python3.6/site-packages/torch_neuron/convert.py", line 105, in trace
    cu.stats_post_compiler(neuron_graph)
  File "/home/matthieu/neuron_stable_venv/lib/python3.6/site-packages/torch_neuron/convert.py", line 424, in stats_post_compiler
    "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

Please find the archive of compiled artifacts directory at aws-neuron-support@amazon.com for further debug.

Thanks!

**Comment by aws-taylor** [comment]
Thanks @Matthieu-Tinycoaching,

  I'm working to reproduce the issue and investigate. We'll keep you posted of our findings.

Regards,
Taylor

**Comment by aws-taylor** [comment]
Hello @Matthieu-Tinycoaching,

I re-ran the script you provided with the current release version of the compiler and was able to successfully compile. If possible, please update your package versions and try again.

Regards,
 Taylor
 
```
Name: neuron-cc
Version: 1.5.5.0+3cc38c60b
Summary: AWS Neuron SDK compiler
Home-page: https://aws.amazon.com/machine-learning/inferentia/
Author: None
Author-email: None
License: AWS Neuron Core Software License Agreement
Location: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages
Requires: dmlc-tvm, inferentia-hwm, islpy, dmlc-nnvm, scipy, networkx, dmlc-topi, numpy
Required-by: 
---
Name: transformers
Version: 4.8.2
Summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
Home-page: https://github.com/huggingface/transformers
Author: Thomas Wolf, Lysandre Debut, Victor Sanh, Julien Chaumond, Sam Shleifer, Patrick von Platen, Sylvain Gugger, Suraj Patil, Stas Bekman, Google AI Language Team Authors, Open AI team Authors, Facebook AI Authors, Carnegie Mellon University Authors
Author-email: thomas@huggingface.co
License: Apache
Location: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages
Requires: huggingface-hub, tqdm, packaging, filelock, requests, numpy, regex, importlib-metadata, pyyaml, dataclasses, sacremoses, tokenizers
Required-by: 
---
Name: torch-neuron
Version: 1.8.1.1.5.12.0
Summary: UNKNOWN
Home-page: UNKNOWN
Author: AWS
Author-email: UNKNOWN
License: Proprietary
Location: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages
Requires: torch
Required-by: 
```

**Comment by micwade-aws** [comment]
@Matthieu-Tinycoaching - Please re-open this if still blocked.
