### ISSUE TITLE
Compilation error for BERT-large using MLPerf saved model

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#286]
Hi AWS experts,

I am trying to compile the MLperf inference BERT-large saved model at https://zenodo.org/record/3939747#.YMwBE_LiuF4

My cmd (saved model file from the above link, official model link from mlperf)
export BERT_LARGE_SAVED_MODEL="/home/ubuntu/aws-neuron-sdk/src/examples/tensorflow/bert_demo/mlperf" 
python bert_no_model.py --input_saved_model $BERT_LARGE_SAVED_MODEL --output_saved_model ./bert-saved-model-neuron

Then got the error below:
Traceback (most recent call last):
  File "bert_no_model.py", line 40, in <module>
    main()
  File "bert_no_model.py", line 13, in main
    pred = tf.contrib.predictor.from_saved_model(args.input_saved_model)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/contrib/predictor/predictor_factories.py", line 153, in from_saved_model
    config=config)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/contrib/predictor/saved_model_predictor.py", line 153, in __init__
    loader.load(self._session, tags.split(','), export_dir)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 349, in load_graph
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 327, in get_meta_graph_def_from_tags
    "\navailable_tags: " + str(available_tags))
RuntimeError: MetaGraphDef associated with tags 'serve' could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: []

Could you help check.
I guess the reason is that to compile the open source BERT model on Inferentia, **the SavedModel has to be generated using estimator.export_saved_model**, and MLperf inference saved model is not using estimator.export_saved_model.

Is it possible to remove that limitation so users can run the MLperf model?

**Comment by jeffhataws** [comment]
Thanks for the detailed info. We will take a look.

**Comment by jeffhataws** [comment]
Hi zqliu19, 

Our converter only uses SaveModel as the interchange format. However, you can convert pb file to SaveModel by using the function here https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/tensorflow/keras_resnet50/pb2sm_compile.py#L24 . By calling this function using 

`pb_to_saved_model("model.pb", {"input_ids:0": "input_ids:0", "input_mask:0" : "input_mask:0", "segment_ids:0": "segment_ids:0"}, {"logits:0" : "logits:0"}, "savedmodel_export")`  

I was able to convert model.pb to savedmodel_export SavedModel. 

Please give it a try and let us know if there's any other issues.

**Comment by zqliu19** [comment]
Thanks a lot @jeffhataws 

I was able to convert model.pb to savedmodel_export SavedModel following your instructions, however,
when we tried to compile the saved model with bert_model.py we got the error below:

Traceback (most recent call last):
  File "bert_model.py", line 258, in <module>
    main()
  File "bert_model.py", line 38, in main
    aggressive_fp16_cast=args.aggressive_optimizations,
  File "bert_model.py", line 135, in __init__
    self.input_ids = predictor.feed_tensors['input_ids']
KeyError: 'input_ids'

cmd:
export BERT_LARGE_SAVED_MODEL="/home/ubuntu/aws-neuron-sdk/src/examples/tensorflow/bert_demo/savedmodel_export"
python bert_model.py --input_saved_model $BERT_LARGE_SAVED_MODEL --output_saved_model ./bert-saved-model-neuron-mlperf-custom --batch_size=6 --aggressive_optimizations

Could you help check?
Also, I didn't see any files (.index, .data) under the folder 'variables' for 'savedmodel_export', is this expected?

**Comment by jeffhataws** [comment]
Hi zqliu19,

Please use bert_no_model.py instead of bert_model.py. With bert_no_model.py, I was able to compile the savedmodel_export:

```
Compiler status PASS
INFO:tensorflow:Number of operations in TensorFlow session: 2385
INFO:tensorflow:Number of operations after tf.neuron optimizations: 2385
INFO:tensorflow:Number of operations placed on Neuron runtime: 2332
INFO:tensorflow:Successfully converted savedmodel_export to compiled
{'OnNeuronRatio': 0.9777777777777777}
```
Thanks.

**Comment by zqliu19** [comment]
Thanks a lot Jeff, we were able to dump a saved_model directly from MLPerf repo, instead of manually converting the pb to sm. And that works for bert_model.py, we can close the ticket now.
