### ISSUE TITLE
BERT-large deploy error , seqlen=384, BS=2 

### ISSUE THREAD

**Issue by zqliu19** [aws/aws-neuron-sdk#296]
We compiled BERT large with seqlen=384, BS=2 using cmd below, and got the compiled model successfully.
python bert_model.py --input_saved_model $BERT_LARGE_SAVED_MODEL --output_saved_model ./bert-saved-model-neuron-mlperf-custom-384-bs2 --batch_size=2 --aggressive_optimizations

However, when we deploy the model, we got the error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 768 values, but the requested shape has 256
         [[{{node bert/encoder/Reshape}}]]

**Comment by zqliu19** [comment]
need to add --sequence_length for compilation
