### ISSUE TITLE
torch.neuron.trace error

### ISSUE THREAD

**Issue by MaritzaH4t1qbit** [aws/aws-neuron-sdk#297]
Hi, 

I am having problems tracing a model:

`coordinates = torch.tensor([[[0.03192167, 0.00638559, 0.01301679],
                            [-0.83140486, 0.39370209, -0.26395324],
                            [-0.66518241, -0.84461308, 0.20759389],
                            [0.45554739, 0.54289633, 0.81170881],
                            [0.66091919, -0.16799635, -0.91037834]]])

species = torch.tensor([[6, 1, 1, 1, 1]])

compiled_model_neuron = torch.neuron.trace(model, tuple([(species, coordinates)])) `

**the output is** 

`WARNING:Neuron:remove_inplace_ops: conversion of AEVComputer#6/aten::index_add_#191 (type aten::index_add_) to its out-of-place counterpart is not yet supported
WARNING:Neuron:remove_inplace_ops: conversion of AEVComputer#6/aten::index_add_#196 (type aten::index_add_) to its out-of-place counterpart is not yet supported
WARNING:Neuron:remove_inplace_ops: conversion of AEVComputer#6/aten::index_add_#477 (type aten::index_add_) to its out-of-place counterpart is not yet supported
INFO:Neuron:There are 130 ops of 22 different types in the TorchScript that are not compiled by neuron-cc: aten::index_put, aten::index, aten::masked_scatter, aten::celu, aten::nonzero, aten::new_zeros, aten::index_add_, aten::prod, aten::cos, aten::acos, aten::cosine_similarity, aten::norm, aten::where, aten::remainder, aten::cumsum, aten::tril_indices, aten::repeat_interleave, aten::unique_consecutive, aten::sort, aten::any, aten::triu_indices, aten::view_as, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 525, fused = 352, percent fused = 67.05%
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$494; falling back to native python function call
ERROR:Neuron:'numpy.ndarray' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 330, in op_converter
    dynamic_batch_size=self.dynamic_batch_size, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 126, in trace
    '--io-config', _io_config(input_tensors, output_tensors)]
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 1097, in _io_config
    outputs = [ts.name for ts in output_tensors]
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 1097, in <listcomp>
    outputs = [ts.name for ts in output_tensors]
AttributeError: 'numpy.ndarray' object has no attribute 'name'
Traceback (most recent call last):
  File "compile.py", line 50, in <module>
    compiled_model_neuron = torch.neuron.trace(ani_model, tuple([(species, coordinates)])) # using neuron.trace
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 107, in trace
    neuron_graph = cu.compile_fused_operators(neuron_graph, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 347, in compile_fused_operators
    neuron_graph(*neuron_graph.example_inputs, op_converter=op_converter)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py", line 178, in __call__
    self.run_op(op, unique_tensor_map, op_converter)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py", line 189, in run_op
    outputs = op(*inputs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/graph.py", line 306, in __call__
    return self.func(self, *inputs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/resolve_function.py", line 55, in func
    return auto_func(**_get_kwargs(op, func_args, args))
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/resolve_function.py", line 71, in _get_kwargs
    'No matching argument info is found for {}'.format(op))
ValueError: No matching argument info is found for <Operation EnergyShifter#8/aten::index_put_#38>`

I am using:
aws_neuron_pytorch_p36
pytorch 1.8.1+cu102
torch_neuron 1.8.1.1.4.1.0

Is the tracing no working because of the unsupported operators in the model?

Thanks

**Comment by aws-renfu** [comment]
Hi MaritzaH4t1qbit,

We are looking into the error above and were able to reproduce similar behavior. We are working towards resolving it.

To be able to determine if this model will be supported by Inferentia, can you confirm which model you are compiling here?

Thanks.

**Comment by MaritzaH4t1qbit** [comment]
Hi Randy, 

Is there an email were  I can share the model information?, 
Thanks,

**Comment by aws-renfu** [comment]
Please contact jlunt@amazon.com.

Thanks!

**Comment by awsrjh** [comment]
please let us know if we can help more
