### ISSUE TITLE
Getting errors trying to set up Tensorflow 2.X on Inf1 following the quickstart guide

### ISSUE THREAD

**Issue by cabal-daniel** [aws/aws-neuron-sdk#320]
According to the instructions for Tensorflow 2.X in this link:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/devflows/ec2-then-ec2-devflow.html#ec2-then-ec2-setenv

I first run `source activate aws_neuron_tensorflow_p36`
then I run the commands
```
# Setup a new Python virtual environment
sudo apt-get install python3-venv
python3 -m venv neuron_tf2_env
source neuron_tf2_env/bin/activate
pip install --upgrade pip
pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com
pip install tensorflow-neuron[cc]
pip install ipykernel
python -m ipykernel install --user --name neuron_tf2 --display-name "Python (Neuron TensorFlow 2)"
pip install jupyter notebook
pip install environment_kernels
```

This installs the general (non-AWS neuron) pip repository's Tensorflow 2.5 lib. When I do `python -c "import tensorflow"` it complains about not having CUDA devices.

So I made sure to do
```
pip install tensorflow-neuron[cc] --no-deps
pip install tensorboard-plugin-neuron --no-deps
pip install tensorboard-neuron --no-deps
```

Now I am getting these errors:
```
>>> import tensorflow.neuron as tfn
2021-09-03 21:16:00.974352: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
2021-09-03 21:16:00.974452: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:105] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.
2021-09-03 21:16:00.999663: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/cpu/lib/python3.7/site-packages/tensorflow/__init__.py", line 444, in <module>
    _ll.load_library(_plugin_dir)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/cpu/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/tensorflow-plugins/libaws_neuron_plugin.so: undefined symbol: _ZNK10tensorflow6Device19IsRemoteCallAllowedEv
```

I have `tensorflow2_latest_p37` activated

**Comment by jeffhataws** [comment]
Hi cabal-daniel,

Thank you for filing the issue. Apologies for the confusion.  

There's an error in the documentation that the "To activate TF 2.x" section is under "Enable TensorFlow-Neuron Conda enviroment". In fact since there's currently no Deep Learning AMI with TF 2.x environment, please do not activate any conda environment first. You can exit the conda environment by doing "conda deactivate" or logout and log back in. 

Instead, follow only the steps under "To activate TensorFlow 2.x" where it shows how to create a Python virtual environment  and install packages needed to run our TensorFlow-Neuron 2.x tutorials. Then go to the tutorial.

We will improve the documentation page to be more clear.

**Comment by cabal-daniel** [comment]
Hi @jeffhataws 

Thank you for the quick response. I followed your instructions and started a brand new Inf1.xlarge with AMI: `Deep Learning AMI (Ubuntu 18.04) Version 49.0 - ami-0e9c522a722725e62`

I skipped `source activate tensorflow2_latest_p37` and just ran the commands `To activate TensorFlow 2.x:` only.

I then ran `python -c "import tensorflow.neuron"` which produced
```
2021-09-03 23:38:10.201798: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-09-03 23:38:12.618622: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-09-03 23:38:13.683430: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-09-03 23:38:13.683488: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-61-100): /proc/driver/nvidia/version does not exist
```

Is this expected? I know the inf1 instance does not have a CUDA device but when I ran the commands previously sourcing the conda built, it used to output
```
2021-09-03 21:16:00.974352: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
2021-09-03 21:16:00.974452: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:105] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.
2021-09-03 21:16:00.999663: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
```

How can I know that my environment is setup correctly and tensorflow env is able to reach the inf1 special ML hardware?

**Comment by jeffhataws** [comment]
Hi cabal-daniel,

You can ignore the error as it is emitted by the installed Google-released TensorFlow (tensorflow pip package) and doesn't impact the functionality of TensorFlow-Neuron. TensorFlow-Neuron (tensorflow-neuron pip package) is a plugin that provides the Neuron support. You can also see the error when using `python -c "import tensorflow"` which doesn't involve Neuron plugin package.

To run on Inferentia, please go ahead and try some examples and the tutorial:

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/api-tracing-python-api.html#example-usage

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/tensorflow/huggingface_bert/huggingface_bert.html

Thanks and let us know if you have further issues.

**Comment by dan-hu-spring** [comment]
Awesome this worked thanks. I'll close the issue.
