### ISSUE TITLE
Use of PyTorch v1.6.0 for latest neuron SDK

### ISSUE THREAD

**Issue by Tagussan** [aws/aws-neuron-sdk#327]
Hi,

I have a project which uses PyTorch v1.6.0 with Torchvision v0.7.0 and I'd like to run this on the Inferentia chip. Because torch-neuron requires torch==1.8.1, I updated PyTorch to v1.8.1 and Torchvision to v0.9.0 in my project and then loaded model files which was trained using PyTorch v1.6.0. However, although the program itself loads the model and runs without error, the inference result is quite different between torch 1.6.0 and 1.8.1 when running on my GPU. So, it would be quite helpful if I can use PyTorch v1.6.0 for Inferentia chip.

Is it possible to use PyTorch v1.6.0 project on Inferentia chip?
Thanks.

**Comment by Tagussan** [comment]
Currently, if I do a forced install of torch==1.6.0, the torch_neuron produces error when compiling a model.

![1 6 0err](https://user-images.githubusercontent.com/3764516/133880888-ca713130-6776-41b6-9d91-2284758b4b3d.PNG)

**Comment by mrnikwaws** [comment]
Hi @Tagussan,

You are correct that we don't currently support PyTorch 1.6.0.  There have now been 3 major releases of PyTorch since v1.6.0, so my recommendation would be to do some analysis on you model to determine why it generates different results.  This may be a bug in PyTorch.  It would also be worth trying PyTorch 1.5 or 1.7 which we do support at this time.  

You can install these with ```pip install torch-neuron==1.5.1``` or ```pip install torch-neuron==1.7.1```  In general we need to limit the number of versions of PyTorch we support to ensure we are testing core use cases and providing our customers with a great experience.

Are you able to share more of your model, or a minimal model that exhibits the same behavior?  It's possible we can offer some advice and give you some recommendations (edited)

**Comment by Tagussan** [comment]
Hi @mrnikwaws 
Thanks for your reply. I agree that the different results may come from a bug in PyTorch. Thanks to your suggestion, tested my project with PyTorch 1.5 and 1.7, and confirmed that PyTorch 1.5 works. So I decided not to dig in the bug and try compiling my project with PyTorch 1.5.

First, I tried to trace my model (not for neuron) with
```
model_trace = torch.jit.trace(image_classification_model, input_tensor)
model_trace.save(trace_save_name)
```
where `image_classification_model` is the model that we would like to compile. It works and torchscript file is successfully saved.

Then, I installed latest torch-neuron for PyTorch 1.5 with `pip3 install "torch-neuron==1.5.*" --extra-index-url https://pip.repos.neuron.amazonaws.com` and tried to compile the model by
```
model_neuron = torch.neuron.trace(image_classification_model, example_inputs=[input_tensor])
```

However, after I execute this, I got the following error:
```
INFO:Neuron:There are 1 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::adaptive_max_pool2d, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)                                   [264/1940]INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 315, fused = 295, percent fused = 93.65%                                                                                                                                                                                                   INFO:Neuron:PyTorch to TF conversion failed to resolve function on prim::Constant with inputs []                                                                                                                                                                                                                 INFO:Neuron:Exception = can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.                                                                                                                                                                              WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$871; falling back to native python function call                                                                                                                                                                                                        ERROR:Neuron:can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.                                                                                                                                                                                         Traceback (most recent call last):                                                                                                                                                                                                                                                                                 File "/home/ubuntu/.local/lib/python3.6/site-packages/torch_neuron/convert.py", line 346, in op_converter                                                                                                                                                                                                          item, inputs, compiler_workdir=sg_workdir, **kwargs)                                                                                                                                                                                                                                                           File "/home/ubuntu/.local/lib/python3.6/site-packages/torch_neuron/decorators.py", line 77, in trace                                                                                                                                                                                                               transform_torch_graph_to_tensorflow(jit_trace, example_inputs, **kwargs)                                                                                                                                                                                                                                       File "/home/ubuntu/.local/lib/python3.6/site-packages/torch_neuron/decorators.py", line 558, in transform_torch_graph_to_tensorflow                                                                                                                                                                                raise e                                                                                                                                                                                                                                                                                                        File "/home/ubuntu/.local/lib/python3.6/site-packages/torch_neuron/decorators.py", line 552, in transform_torch_graph_to_tensorflow                                                                                                                                                                                tensor_outputs = local_func(op, *tensor_inputs)                                                                                                                                                                                                                                                                File "/home/ubuntu/.local/lib/python3.6/site-packages/torch_neuron/ops/prim.py", line 30, in Constant                                                                                                                                                                                                              tensor = tf.constant(tensor)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 161, in constant_v1
    allow_broadcast=False)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 427, in make_tensor_proto
    values = np.asarray(values)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/tensor.py", line 492, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 315, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 15 [supported]
INFO:Neuron: => aten::_convolution: 85 [supported]
INFO:Neuron: => aten::adaptive_avg_pool2d: 17 [supported]
INFO:Neuron: => aten::adaptive_max_pool2d: 1 [not supported]
INFO:Neuron: => aten::add: 16 [supported]
INFO:Neuron: => aten::addmm: 2 [supported]
INFO:Neuron: => aten::batch_norm: 53 [supported]
INFO:Neuron: => aten::cat: 1 [supported]
INFO:Neuron: => aten::contiguous: 1 [supported]
INFO:Neuron: => aten::div: 1 [supported]
INFO:Neuron: => aten::expand: 1 [supported]
INFO:Neuron: => aten::max_pool2d: 1 [supported]
INFO:Neuron: => aten::mul: 18 [supported]
INFO:Neuron: => aten::permute: 1 [supported]
INFO:Neuron: => aten::relu: 66 [supported]
INFO:Neuron: => aten::sigmoid: 16 [supported]
INFO:Neuron: => aten::size: 11 [supported]
INFO:Neuron: => aten::t: 2 [supported]
INFO:Neuron: => aten::to: 2 [supported]
INFO:Neuron: => aten::unsqueeze: 1 [supported]
INFO:Neuron: => aten::view: 4 [supported]
```

I read the message `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.` and thought that casting everything to cpu would solve the problem. So I modified my code:
```
model_neuron = torch.neuron.trace(image_classification_model.cpu(), example_inputs=[input_tensor.cpu()])
```

However, I got the following error after the execution (Since the generated error is very long, I picked up some lines that may contain useful information):
```
.....
self = MyCNNModel(
  (criterion): CrossEntropyLoss()
  (encoder): Sequential(
    (0): Sequential(
      (conv1): ...t_features=512, bias=True)
    (3): ReLU(inplace=True)
  )
  (fc): Linear(in_features=512, out_features=2, bias=True)
)
x = tensor([[[[0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
          [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9...0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]]],
       dtype=torch.float16)

    def forward(self, x):
        # x: bs x N x C x W x W
        bs, n, ch, w, h = x.shape
        x = x.view(bs * n, ch, w, h)  # x: N bs x C x W x W
        with torch.backends.cudnn.flags(deterministic=True, benchmark=True):
>           x = self.encoder(x)  # x: N bs x C' x W' x W'

myproject/models/cnn_model.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _                                                                                                                                                                                                                                                                                                              self = Sequential(
(0): Sequential(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=Fals...e)
        (fc2): Conv2d(128, 2048, kernel_size=(1, 1), stride=(1, 1))
        (sigmoid): Sigmoid()
      )
    )
  )
)
input = (tensor([[[[0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
          [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0....00, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]]],
       dtype=torch.float16),), kwargs = {}

    def __call__(self, *input, **kwargs):
        for hook in self._forward_pre_hooks.values():
            result = hook(self, input)
            if result is not None:
                if not isinstance(result, tuple):
                    result = (result,)
                input = result                                                                                                                                                                                                                                                                                           if torch._C._get_tracing_state():
>           result = self._slow_forward(*input, **kwargs)

../.local/lib/python3.6/site-packages/torch/nn/modules/module.py:548:
.....
(long lines of error omitted)
.....
self = Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
input = tensor([[[[0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
          [0.9961, 0.9961, 0.9961,  ..., 0.9961, 0.9...0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]]],
       dtype=torch.float16)
weight = Parameter containing:
tensor([[[[ 2.9932e-01, -1.1553e+00, -1.8955e+00,  ...,  2.3164e+00,
           -2.6113e+00,  2.... 4.3848e-01,  1.9092e+00,  6.3477e-01,  ...,  1.6230e+00,
            3.6694e-01, -1.8726e-01]]]], dtype=torch.float16)

    def _conv_forward(self, input, weight):
        if self.padding_mode != 'zeros':
            return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
                            weight, self.bias, self.stride,
                            _pair(0), self.dilation, self.groups)                                                                                                                                                                                                                                                        return F.conv2d(input, weight, self.bias, self.stride,
>                       self.padding, self.dilation, self.groups)
E       RuntimeError: "unfolded2d_copy" not implemented for 'Half'

../.local/lib/python3.6/site-packages/torch/nn/modules/conv.py:350: RuntimeError
                                                                                                                                                                                                                                                                                                                 During handling of the above exception, another exception occurred:
....
(long lines of error omitted)
....

    @contextmanager
    def torch_trace_error_handler():
        try:
            yield
        except RuntimeError as e:
            trace_error_msg = '{}\n\ntorch.jit.trace failed with following error: {}'.format(_jit_trace_error_message, e)
>           raise RuntimeError(trace_error_msg)                                                                                                                                                                                                                                                                  E           RuntimeError: torch.jit.trace error. The PyTorch-Neuron trace Python API uses the
E           torch.jit.trace function in PyTorch to generate ScriptFunction models for execution
E           on Inferentia. Due to this, your exisiting PyTorch model must be torch jit traceable.
E
E           Please visit https://pytorch.org/docs/stable/generated/torch.jit.trace.html
E           to review the properties that a model must have to be torch jit traceable.
E           The PyTorch-Neuron trace API accepts torch.jit.trace kwargs, such as `strict=False`.
E
E           For more information on troubleshooting compiling models using the PyTorch-Neuron                                                                                                                                                                                                                    E           trace API, please visit https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/troubleshooting-guide.html.
E
E           torch.jit.trace failed with following error: "unfolded2d_copy" not implemented for 'Half'

../.local/lib/python3.6/site-packages/torch_neuron/decorators.py:1806: RuntimeError
```
It seems that half precision convolution is not supported with CPU execution in PyTorch. It is true that my model contains half precision weights.
Is it possible to compile models with `torch-neuron` that has half precision weights?

> Are you able to share more of your model, or a minimal model that exhibits the same behavior? It's possible we can offer some advice and give you some recommendations

I'm sorry to say but it is difficult to share our entire model due to intellectual property. But it is possible to share a minimal model that cause the same error, although it will take some time. I wonder if we can solve the gpu and half precision problems above with some workaround first.

**Comment by Tagussan** [comment]
I found a workaround. PyTorch 1.5.1 tries to convert a tensor which is on GPU to ndarray, so I modified the PyTorch code. I rewrite [these lines](https://github.com/pytorch/pytorch/blob/3c31d73c875d9a4a6ea8a843b9a0d1b19fbe36f3/torch/tensor.py#L490-L494) to:
```
    def __array__(self, dtype=None):
        if dtype is None:
            return self.cpu().numpy()
        else:
            return self.cpu().numpy().astype(dtype, copy=False)
```
Then `model_neuron = torch.neuron.trace(image_classification_model, example_inputs=[input_tensor])` is executed properly and the above error vanished. The neuron-cc compiler started to work. 

However, I got another problem. After neuron-cc started working, I got the following error:
```
...................................
...std::vector<bir::MemoryLocation*> dfs_topo_sort(bir::Function&)
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*****************************.*********************....................................std::vector<bir::MemoryLocation*> dfs_topo_sort(bir::Function&)
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************.....................09/27/2021 11:56:49 AM CRITICAL [WalrusDriver]: too many reloads required                                                                                                                 09/27/2021 11:56:50 AM ERROR [neuron-cc]: ***************************************************************                                                                                                                                                        09/27/2021 11:56:50 AM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
09/27/2021 11:56:50 AM ERROR [neuron-cc]: ***************************************************************                                                                                                                                                        09/27/2021 11:56:50 AM ERROR [neuron-cc]:
09/27/2021 11:56:50 AM ERROR [neuron-cc]: Error message:  A process in the process pool was terminated abruptly while the future was running or pending.                                                                                                         09/27/2021 11:56:50 AM ERROR [neuron-cc]:
09/27/2021 11:56:50 AM ERROR [neuron-cc]: Error class:    BrokenProcessPool
09/27/2021 11:56:50 AM ERROR [neuron-cc]: Error location: pipeline.compile.0                                                                                                                                                                                     09/27/2021 11:56:50 AM ERROR [neuron-cc]: Command line:   /home/ubuntu/.local/bin/neuron-cc compile /tmp/tmpkwcsv3at/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpkwcsv3at/graph_def.neff --io-config '{"inputs": {"tensor.1:0": [[1, 5, 3, 384, 384], "float16"]}, "outputs": ["Reshape_2:0"]}' --verbose 35
09/27/2021 11:56:50 AM ERROR [neuron-cc]:
09/27/2021 11:56:50 AM ERROR [neuron-cc]: Internal details:
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 244, in neuroncc.driver.Job.runSingleInputFn
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput                                                                                                                     09/27/2021 11:56:50 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 286, in neuroncc.driver.Job.SingleInputJob.run                                                                                                                                   09/27/2021 11:56:50 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 291, in neuroncc.driver.Job.SingleInputJob.run                                                                                                                                   09/27/2021 11:56:50 AM ERROR [neuron-cc]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result                                                                                                                                           09/27/2021 11:56:50 AM ERROR [neuron-cc]:     return self.__get_result()
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result                                                                                                                                     09/27/2021 11:56:50 AM ERROR [neuron-cc]:     raise self._exception
09/27/2021 11:56:50 AM ERROR [neuron-cc]:
09/27/2021 11:56:50 AM ERROR [neuron-cc]: Version information:
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   Neuron Compiler version 1.6.13.0+9f61b2f75
09/27/2021 11:56:50 AM ERROR [neuron-cc]:
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   HWM version 1.6.0.0-0
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   NEFF version Dynamic
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   TVM version 1.6.2.0+0
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   NumPy version 1.19.5
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   MXNet not available
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   TF not available
09/27/2021 11:56:50 AM ERROR [neuron-cc]:   ONNX not available
09/27/2021 11:56:50 AM ERROR [neuron-cc]:
09/27/2021 11:56:50 AM ERROR [neuron-cc]: Artifacts stored in: /tmp/tmpkwcsv3at

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
```

I'm compiling this on `g4dn.4xlarge` EC2 instance and confirmed that there was enough free RAM when this error is produced. This seems an internal compiler error. How may I fix this?

**Comment by mrnikwaws** [comment]
Hi  @Tagussan,

Can you please try the following?:

1. Please downgrade your version of numpy using ```pip install numpy==1.18.5``` this may be the source of some issues.  See if that allow compilation to succeed.  We're aware of this issue in the current installation instructions and are working to resolve it.
2. If the problem continues please add the argument compiler_workdir="compile_artifacts" to the torch.neuron.trace command.  This will generate a local directory ('compile_artifacts') with some artifacts we can use to debug your issue.  If you tar + gzip this file we can work on a way to share it with the team for further debug on our end.

**Comment by Tagussan** [comment]
Hi @mrnikwaws 

I did `pip install numpy==1.18.5` and run compilation again, but I got the same error. So may I try option 2? I really appreciate that your team help me compiling the model. I'd like to share the artifacts with your team.

However, before sharing the artifacts, I'd like to confirm the following things:
1. Can I share `compile_artifacts.tar.gz` with your team in a private manner? (I don't want to make the log public)
1. Does the artifacts contain the information of CNN model structure and weights? If so, is it possible to make a contract with you that your team uses this log only for debugging and do not reverse engineer our model?

**Comment by aws-diamant** [comment]
Hi @Tagussan ,

Thanks for trying `numpy==1.18.5`.
Yes, let's proceed to option #2 for debugging the compilation error.

Regarding your questions:
1.  Please contact aws-neuron-support@amazon.com for sharing the artifacts privately.
2. The artifacts contain the PB file, which does include the frozen weights (these will be decoupled in the future). If it's not too much trouble, I suggest to compile with random-weights for now for the sake of artifacts sharing.

**Comment by Tagussan** [comment]
Hi, @aws-diamant 

Thanks for sharing the contact address. I've sent an e-mail.

**Comment by Tagussan** [comment]
Hi @awsrjh ,
Thanks for your comment. I've updated the neuron version as discussed with you in [this thread](https://github.com/aws/aws-neuron-sdk/issues/352#issuecomment-957023854).

After the update, I succeeded in compiling the model already discussing here. This model is a simplified model of the actual production model, whose back-bone structure is replaced with a simpler one.

Then I tried to compile the actual production model. However, I faced other error message and failed to compile. Because the error message is so long, I pasted it here: https://gist.github.com/Tagussan/39fb7b3a3cd3316db61d58e84c687b0a

**Comment by AWShtokoyo** [comment]
Reopened this as @Tagussan is still working on this and shared the model for reviewing.

**Comment by Tagussan** [comment]
Thank you for reopening this. I shared the compiler artifacts with the AWS team and they are kindly digging into this issue now.

**Comment by Tagussan** [comment]
@awsrjh 
Hi, is there any updates on this issue? Thanks!

**Comment by aws-taylor** [comment]
Hello @Tagussan,

 We have identified the issue and the fix will be released with 1.17. Please let me know if you have any further issues.

-Taylor

**Comment by awsrjh** [comment]
to update the thread: We are working with Tagussan on this.

**Comment by aws-zejdaj** [comment]
Hi @Tagussan We have updated the compilation progress interface as part of issue 352. Please try with the Neuron https://github.com/aws/aws-neuron-sdk/releases/tag/v1.17.0 (or newer)  and reopen if you still not working for you.

**Comment by Tagussan** [comment]
@aws-zejdaj Hi,
This indeed worked for me. Thank you for your support!
