### ISSUE TITLE
Internal compiler error related to: llvm::StringSwitch<T, R>::operator R() [with T = bir::Dtype; R = bir::Dtype]: Assertion `Result && "Fell off the end of a string-switch"' failed.

### ISSUE THREAD

**Issue by Tagussan** [aws/aws-neuron-sdk#339]
Hi, 
I have a problem with compiling my private model. Here's the error produced:
```
INFO:Neuron:There are 2 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: prim::PythonOp, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 17, fused = 17, percent fused = 100.0%
INFO:Neuron:Compiling function _NeuronGraph$47 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmp3wcn7ioy/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp3wcn7ioy/graph_def.neff --io-config {"inputs": {"0:0": [[1, 25], "float32"]}, "outputs": ["add_2:0"]} --verbose 35'
.Analyzing dependencies of sg00/Block1
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Compiler status PASS
INFO:Neuron:Compiling function _NeuronGraph$48 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpx2txkktj/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpx2txkktj/graph_def.neff --io-config {"inputs": {"0:0": [[1, 512], "float32"]}, "outputs": ["add_2:0"]} --verbose 35'
.Analyzing dependencies of sg00/Block1
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Compiler status PASS
INFO:Neuron:Compiling function _NeuronGraph$49 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpxw3d4b7g/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpxw3d4b7g/graph_def.neff --io-config {"inputs": {"0:0": [[1, 128], "float32"]}, "outputs": ["Cast_1:0"]} --verbose 35'
.python3.6: /opt/brazil-pkg-cache/packages/LLVM/LLVM-9.x.1263.0/AL2_x86_64/DEV.STD.PTHREAD/build/include/llvm/ADT/StringSwitch.h:189: llvm::StringSwitch<T, R>::operator R() [with T = bir::Dtype; R = bir::Dtype]: Assertion `Result && "Fell off the end of a string-switch"' failed.
10/08/2021 09:28:48 AM ERROR [neuron-cc]: ***************************************************************
10/08/2021 09:28:48 AM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
10/08/2021 09:28:48 AM ERROR [neuron-cc]: ***************************************************************
10/08/2021 09:28:48 AM ERROR [neuron-cc]:
10/08/2021 09:28:48 AM ERROR [neuron-cc]: Error message:  A process in the process pool was terminated abruptly while the future was running or pending.
10/08/2021 09:28:48 AM ERROR [neuron-cc]:
10/08/2021 09:28:48 AM ERROR [neuron-cc]: Error class:    BrokenProcessPool
10/08/2021 09:28:48 AM ERROR [neuron-cc]: Error location: pipeline.compile.0
10/08/2021 09:28:48 AM ERROR [neuron-cc]: Command line:   /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpxw3d4b7g/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpxw3d4b7g/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 128], "float32"]}, "outputs": ["Cast_1:0"]}' --verbose 35
10/08/2021 09:28:48 AM ERROR [neuron-cc]:
10/08/2021 09:28:48 AM ERROR [neuron-cc]: Internal details:
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 244, in neuroncc.driver.Job.runSingleInputFn
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 286, in neuroncc.driver.Job.SingleInputJob.run
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 291, in neuroncc.driver.Job.SingleInputJob.run
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/concurrent/futures/_base.py", line 432, in result
10/08/2021 09:28:48 AM ERROR [neuron-cc]:     return self.__get_result()
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
10/08/2021 09:28:48 AM ERROR [neuron-cc]:     raise self._exception
10/08/2021 09:28:48 AM ERROR [neuron-cc]:
10/08/2021 09:28:48 AM ERROR [neuron-cc]: Version information:
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   Neuron Compiler version 1.6.13.0+9f61b2f75
10/08/2021 09:28:48 AM ERROR [neuron-cc]:
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   HWM version 1.6.0.0-0
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   NEFF version Dynamic
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   TVM version 1.6.2.0+0
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   NumPy version 1.18.5
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   MXNet not available
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   TF not available
10/08/2021 09:28:48 AM ERROR [neuron-cc]:   ONNX not available
10/08/2021 09:28:48 AM ERROR [neuron-cc]:
10/08/2021 09:28:48 AM ERROR [neuron-cc]: Artifacts stored in: /tmp/tmpxw3d4b7g

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$49; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpxw3d4b7g/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpxw3d4b7g/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 128], "float32"]}, "outputs": ["Cast_1:0"]}' --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 346, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 196, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpxw3d4b7g/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpxw3d4b7g/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 128], "float32"]}, "outputs": ["Cast_1:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 17, compiled = 7, percent compiled = 41.18%
INFO:Neuron:The neuron partitioner created 3 sub-graphs
INFO:Neuron:Neuron successfully compiled 2 sub-graphs, Total fused subgraphs = 3, Percent of model sub-graphs successfully compiled = 66.7%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::addmm: 2
INFO:Neuron: => aten::batch_norm: 2
INFO:Neuron: => aten::dropout: 1
INFO:Neuron: => aten::t: 2
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 2 [supported]
INFO:Neuron: => aten::addmm: 1 [supported]
INFO:Neuron: => aten::div: 1 [supported]
INFO:Neuron: => aten::dropout: 1 [supported]
INFO:Neuron: => aten::expand: 1 [supported]
INFO:Neuron: => aten::size: 2 [supported]
INFO:Neuron: => aten::t: 1 [supported]
INFO:Neuron: => aten::unsqueeze: 1 [supported]
WARNING:Neuron:torch.neuron.trace was unable to compile > 50% of the operators in the compiled model!
WARNING:Neuron:Please review the torch.neuron.analyze_model output and if you believe you are seeing a failure
WARNING:Neuron:Lodge an issue on https://github.com/aws/aws-neuron-sdk/issues if you believe the model is not compiling as expected
Finished loading model, total used 100 iterations
Finished loading model, total used 100 iterations
```

I've met several internal compiler errors before, but the message: 
```
.python3.6: /opt/brazil-pkg-cache/packages/LLVM/LLVM-9.x.1263.0/AL2_x86_64/DEV.STD.PTHREAD/build/include/llvm/ADT/StringSwitch.h:189: llvm::StringSwitch<T, R>::operator R() [with T = bir::Dtype; R = bir::Dtype]: Assertion `Result && "Fell off the end of a string-switch"' failed. 
``` 
is the first one to me.

Do you have any workaround for this? Thanks.

**Comment by Tagussan** [comment]
Hi @awsilya (Дорогой Илья),

I've send an email to aws-neuron-support@amazon.com (and some other members already discussing) containing the compiler artifacts for this issue. Please have a check. Hope to discuss on e-mail.

Спасибо
