### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'input': forward function expects an input argument

### ISSUE THREAD

**Issue by panabee** [aws/aws-neuron-sdk#377]
The Inferentia business team suggested filing an issue here.

We offer a text-to-art service and are trying to port the model to Inferentia but running into compilation issues.

The trace function runs the forward function of our model during compilation.

In our case, the forward function expects an input argument and throws the error below.

How can we fix this?

Thanks.

```
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/_jit_internal.py:651: LightningDeprecationWarning: The `LightningModule.datamodule` property is deprecated in v1.3 and will be removed in v1.5. Access the datamodule through using `self.trainer.datamodule` instead.
  if hasattr(mod, name):
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/_jit_internal.py:651: LightningDeprecationWarning: The `LightningModule.loaded_optimizer_states_dict` property is deprecated in v1.4 and will be removed in v1.6.
  if hasattr(mod, name):
Traceback (most recent call last):
  File "predictor_text_art.py", line 29, in <module>
    from text_art.project import run
  File "/home/ubuntu/text-art-api-bin/text-art-api-bin/text_art/project.py", line 258, in <module>
    model_neuron = torch.neuron.trace(model, global_embed)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 150, in trace
    neuron_graph, jit_trace = to_graph(func, example_inputs, return_trace=True, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 229, in to_graph
    jit_trace = torch.jit.trace(func_or_mod, example_inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 744, in trace
    _module_class,
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 959, in trace_module
    argument_names,
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'
```

**Comment by shebbur-aws** [comment]
Hello @panabee,

Thank you for reporting the issue. Could you please confirm if you are able to trace your model in regular pytorch and generate torchscript before attempting to compile it for Neuron?

Thanks,
Shruthi

**Comment by panabee** [comment]
Hi Shruthi. Yes, we're able to. What do you recommend as next steps?

**Comment by shebbur-aws** [comment]
Hello @panabee,

Thank you for checking. If you can share with us the model you are using, we can try to reproduce the problem on our end and look into it. If you prefer, you could also send it to us at aws-neuron-support@amazon.com. 

Thanks,
Shruthi.

**Comment by shebbur-aws** [comment]
Hello @panabee,

The model you are referring to uses a backward pass and an optimizer. Inferentia chip used in Inf1 instances is an inference chip and supports forward passes only. So this model can’t be supported by Inf1 instances. Neuron will not support this functionality on Inf1. Please re-open the issue if you can provide another example without backward pass and an optimizer.
 
 Thanks,
Shruthi.
