### ISSUE TITLE
Internal Compiler Error 

### ISSUE THREAD

**Issue by saraRaris** [aws/aws-neuron-sdk#422]
I'm getting an Internal Compiler Error when trying to compile models from [mmpose repo](https://github.com/open-mmlab/mmpose).  
I have tried with two different models: hrnet_w48_coco_wholebody_256x192 and 4xmspn50_coco_256x192. Both of them produce the same error although all the operators should be able to be compiled.

The code I'm using is the following:

```
import numpy as np
import cv2
import mmcv
from mmcv.parallel import collate

import torch_neuron
import torch

from mmpose.apis import init_pose_model
from mmpose.core.post_processing import get_affine_transform
from torchvision.transforms import functional as F


def save_info(bbox):

    center, scale = _box2cs(bbox)

    #Save info
    bbox_info = {}
    bbox_info['scale'] = scale
    bbox_info['center'] = center
    bbox_info['bbox_id'] = 0

    return bbox_info


def prepocess_im(im, c, s, r, device):

    #image_size = [288, 384]
    image_size = [192, 256]
    trans = get_affine_transform(c, s, r, image_size)
    img = cv2.warpAffine(im,trans, (int(image_size[0]), int(image_size[1])),flags=cv2.INTER_LINEAR)
    image = F.to_tensor(img)
    im_mean=[0.485, 0.456, 0.406]
    im_std=[0.229, 0.224, 0.225]
    image = F.normalize(image, mean=im_mean, std=im_std)
    image = image.to(device)

    return image


def _box2cs(box):
    """This encodes bbox(x,y,w,h) into (center, scale)

    Args:
        x, y, w, h

    Returns:
        tuple: A tuple containing center and scale.

        - np.ndarray[float32](2,): Center of the bbox (x, y).
        - np.ndarray[float32](2,): Scale of the bbox w & h.
    """

    x, y, w, h = box[:4].cpu()
    input_size = [192, 256] #input size of the model
    aspect_ratio = input_size[0] / input_size[1]
    center = np.array([x + w * 0.5, y + h * 0.5], dtype=np.float32)

    if w > aspect_ratio * h:
        h = w * 1.0 / aspect_ratio
    elif w < aspect_ratio * h:
        w = h * aspect_ratio

    # pixel std is 200.0
    scale = np.array([w / 200.0, h / 200.0], dtype=np.float32)

    scale = scale * 1.25

    return center, scale


#Init model
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = init_pose_model(configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/4xmspn50_coco_256x192.py', '4xmspn50_coco_256x192-7b837afb_20201123.pth', device=device)

#Person detector output example
person_results = torch.tensor([[292.21881, 259.55707,  36.04736,  49.27658,   0.49272,   0.00000]])

#Structure data to feed to pose detection model
im = np.random.randint(255, size=(1080,1920,3),dtype=np.uint8)

img_metas = {}
img_metas['image'] = im
img_metas['bboxes_info'] = []

for bbox in person_results:
    bbox_info = save_info(bbox)
    img_metas['bboxes_info'].append(bbox_info)

#Convert to tensorshape
batch_data = []
for bbox in img_metas['bboxes_info']:
    tens = prepocess_im(im, bbox['center'], bbox['scale'], 0, device)
    batch_data.append(tens)
tens = collate(batch_data, samples_per_gpu=1)

#Compile model
model_neuron = torch.neuron.trace(model, tens)
```

These are the logs showing the error:

```
INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 1059, fused = 1058, percent fused = 99.91%
INFO:Neuron:Compiling function _NeuronGraph$3371 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmp7vwqqekx/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp7vwqqekx/graph_def.neff --io-config {"inputs": {"0:0": [[1, 3, 256, 192], "float32"]}, "outputs": []} --verbose 35'
.04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: ***************************************************************
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:  An Internal Compiler Error has occurred
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: ***************************************************************
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: 
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: Error message:  ERROR: NEFF archive without accelerator or cpu compute ops is not supported. Please check that your model has non-constant computation that is dependent on the inputs listed in --io-config
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: 
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: Error class:    AssertionError
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: Error location: Unknown
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: Command line:   /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmp7vwqqekx/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp7vwqqekx/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 256, 192], "float32"]}, "outputs": []}' --verbose 35
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: 
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: Internal details:
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/CommandDriver.py", line 224, in neuroncc.driver.CommandDriver.CommandDriver.run
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 551, in neuroncc.driver.commands.CompileCommand.CompileCommand.run
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 529, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 533, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 427, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 377, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 378, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 399, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   File "neuroncc/driver/jobs/support/Partitioning.py", line 205, in neuroncc.driver.jobs.support.Partitioning.HhSubgraphs.__init__
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: 
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: Version information:
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   Neuron Compiler version 1.10.3.0+5c3cfc888
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   HWM version 1.10.0.0-0
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   NEFF version Dynamic
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   TVM version 1.10.0.0+0
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   NumPy version 1.19.5
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   MXNet not available
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]:   TF not available
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: 
04/19/2022 09:09:57 AM ERROR 1203 [neuron-cc]: Artifacts stored in: /tmp/tmp7vwqqekx

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$3371; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmp7vwqqekx/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp7vwqqekx/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 256, 192], "float32"]}, "outputs": []}' --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py", line 221, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmp7vwqqekx/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp7vwqqekx/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 256, 192], "float32"]}, "outputs": []}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 1059, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::_convolution: 293 [supported]
INFO:Neuron: => aten::add: 184 [supported]
INFO:Neuron: => aten::batch_norm: 292 [supported]
INFO:Neuron: => aten::relu: 261 [supported]
INFO:Neuron: => aten::to: 1 [supported]
INFO:Neuron: => aten::upsample_nearest2d: 28 [supported]
Traceback (most recent call last):
  File "convert_pose.py", line 108, in <module>
    model_neuron = torch.neuron.trace(model, tens)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 168, in trace
    cu.stats_post_compiler(neuron_graph)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 500, in stats_post_compiler
    "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

**Comment by jeffhataws** [comment]
Based on the error log, it seems that the model that’s sent to the compiler has no outputs. Also, when I change the torch.neuron.trace line to "result = model(tens)", I get the following error which indicates problem in the input structure:
```
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-94-158:~/gh422/mmpose$ python test.py
load checkpoint from local path: 4xmspn50_coco_256x192-7b837afb_20201123.pth
Traceback (most recent call last):
  File "test.py", line 99, in <module>
    result = model(tens)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/gh422/mmpose/mmpose/models/detectors/top_down.py", line 139, in forward
    **kwargs)
  File "/home/ubuntu/gh422/mmpose/mmpose/models/detectors/top_down.py", line 155, in forward_train
    output, target, target_weight)
  File "/home/ubuntu/gh422/mmpose/mmpose/models/heads/topdown_heatmap_multi_stage_head.py", line 466, in get_loss
    assert target.dim() == 5 and target_weight.dim() == 4
AttributeError: 'NoneType' object has no attribute 'dim'
```
It is a good idea to make sure inference of the model on CPU is successful using the inputs you’re using for compilation.

**Comment by saraRaris** [comment]
My mistake, I realized I was using an older version of the repo which let me load the model to cpu and perform an inference following the structure I shared above. 
I was also able to fix the issue I was experiencing and could compile `hrnet_w48_coco_wholebody_256x192`. However, I have been unsuccessful with the other model I was interested in: `4xmspn50_coco_256x192`. Although I'm able to trace it with _torch.jit.trace()_ function this fails for the neuron compiler. From the error I'm getting I understand there's an operation which hasn't been implemented yet and wanted to ask if this will be included in the future.

Below you can see the error I get for 4xmspn5:
```
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 749, fused = 749, percent fused = 100.0%
INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::upsample_bilinear2d with inputs [<tf.Tensor 'Relu_49:0' shape=(1, 256, 8, 6) dtype=float32>, [16, 12], True, None]
INFO:Neuron:Exception = Operator translation failed in 'Bilinear Upsampling with `align_corners=True` is not yet implemented. Please consider using ConvTranspose2d instead.
```

**Comment by hannanjgaws** [comment]
Great to hear that you were able to successfully compile your `hrnet_w48_coco_wholebody_256x192` model!

We currently do not support bilinear upsampling with `align_corners=True`. However, there are a few ways that you can get around this:

1. Use bilinear upsampling with `align_corners=False`
2. Use another upsampling operator, such as nearest neighbors or ConvTranspose2d
3. Force bilinear upsampling with `align_corners=True` to be partitioned onto CPU as follows:
```
supported_ops = set(torch_neuron.get_supported_operations()) - set(['aten::upsample_bilinear2d'])
trace = torch_neuron.trace(model, example_inputs, op_whitelist=supported_ops)
```

Please let us know if one of these approaches enables you to successfully compile your `4xmspn50_coco_256x192` model variant on Neuron.

**Comment by saraRaris** [comment]
Hi, it worked with bilinear upsampling with `align_corners=False`. Thanks a lot for your help!
