### ISSUE TITLE
Compiling Bart doesn't work

### ISSUE THREAD

**Issue by naor2013** [aws/aws-neuron-sdk#431]
I have a Bart model from hugging face transformers.
I tried to compile it using [this tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html) with the correct torch/transformers versions.

The encoder was compiled successfully but the decoder failed:

```INFO:Neuron:There are 2 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 1551, fused = 1545, percent fused = 99.61%
/home/ubuntu/pytorch_venv/lib/python3.7/site-packages/torch/tensor.py:593: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
INFO:Neuron:Number of neuron graph operations 3374 did not match traced graph 2891 - using heuristic matching of hierarchical information
INFO:Neuron:Compiling function _NeuronGraph$984 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/pytorch_venv/bin/neuron-cc compile /tmp/tmphgasdalg/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmphgasdalg/graph_def.neff --io-config {"inputs": {"0:0": [[4, 200], "int64"], "1:0": [[4, 200, 1024], "float32"], "2:0": [[200, 1024], "float32"], "3:0": [[4, 200, 1024], "float32"], "tensor:0": [[], "int64"]}, "outputs": ["aten_add/add:0"]} --verbose 35'
.....INFO:Neuron:Compile command returned: -9
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$984; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/pytorch_venv/bin/neuron-cc compile /tmp/tmphgasdalg/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmphgasdalg/graph_def.neff --io-config '{"inputs": {"0:0": [[4, 200], "int64"], "1:0": [[4, 200, 1024], "float32"], "2:0": [[200, 1024], "float32"], "3:0": [[4, 200, 1024], "float32"], "tensor:0": [[], "int64"]}, "outputs": ["aten_add/add:0"]}' --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/pytorch_venv/lib/python3.7/site-packages/torch_neuron/convert.py", line 382, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/pytorch_venv/lib/python3.7/site-packages/torch_neuron/decorators.py", line 220, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/pytorch_venv/bin/neuron-cc compile /tmp/tmphgasdalg/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmphgasdalg/graph_def.neff --io-config '{"inputs": {"0:0": [[4, 200], "int64"], "1:0": [[4, 200, 1024], "float32"], "2:0": [[200, 1024], "float32"], "3:0": [[4, 200, 1024], "float32"], "tensor:0": [[], "int64"]}, "outputs": ["aten_add/add:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 1551, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 312 [supported]
INFO:Neuron: => aten::ScalarImplicit: 2 [supported]
INFO:Neuron: => aten::add: 171 [supported]
INFO:Neuron: => aten::arange: 2 [supported]
INFO:Neuron: => aten::bmm: 48 [supported]
INFO:Neuron: => aten::contiguous: 96 [supported]
INFO:Neuron: => aten::detach: 1 [supported]
INFO:Neuron: => aten::dropout: 73 [supported]
INFO:Neuron: => aten::embedding: 2 [not supported]
INFO:Neuron: => aten::eq: 2 [supported]
INFO:Neuron: => aten::gelu: 12 [supported]
INFO:Neuron: => aten::layer_norm: 37 [supported]
INFO:Neuron: => aten::masked_fill: 12 [supported]
INFO:Neuron: => aten::matmul: 121 [supported]
INFO:Neuron: => aten::mul: 122 [supported]
INFO:Neuron: => aten::size: 98 [supported]
INFO:Neuron: => aten::softmax: 24 [supported]
INFO:Neuron: => aten::sum: 1 [supported]
INFO:Neuron: => aten::t: 121 [supported]
INFO:Neuron: => aten::to: 1 [supported]
INFO:Neuron: => aten::transpose: 123 [supported]
INFO:Neuron: => aten::unsqueeze: 25 [supported]
INFO:Neuron: => aten::view: 145 [supported]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    max_decoder_length=max_decoder_length,
  File "/home/ubuntu/neuron_generator.py", line 115, in trace
    self.decoder = torch_neuron.trace(decoder, inputs)
  File "/home/ubuntu/pytorch_venv/lib/python3.7/site-packages/torch_neuron/convert.py", line 184, in trace
    cu.stats_post_compiler(neuron_graph)
  File "/home/ubuntu/pytorch_venv/lib/python3.7/site-packages/torch_neuron/convert.py", line 493, in stats_post_compiler
    "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!

I'm using a inf1 EC2 server, all versions of neuron are up to date, torch 1.7.1 and transformers 4.0.1 like the tutorial requires.
What am I doing wrong?

**Comment by mrnikwaws** [comment]
Hi Naor,

The most recent version of torch-neuron should provide an updated message in this case, that reflects the typical cause for this failure mode. 

```
INFO:Neuron:Compile command returned: -9
```

This message indicates that the compiler process was killed.  Normally this is due to the the OOM (out of memory) killer (run by the linux operating system) killing the compilation process due to memory exhaustion. MarianMT and BART are related models in the Hugging Face code base, so changes of the kind in the tutorial should allow compilation.  We recommend you try compiling on an instance with more memory (RAM).

Please let us know if this does not resolve your problem, and we'll investigate, otherwise we'll aim to close this issue in the next few days.

**Comment by aws-mvaria** [comment]
Hi Naor,

We hope the above message has resolved your problem. Please re-open if you require further assistance.
