### ISSUE TITLE
Template for Inferentia T5 

### ISSUE THREAD

**Issue by Ierezell** [aws/aws-neuron-sdk#443]
Hello, 

It's not an issue but I struggled to make T5 work and I just wanted to share it, as I think many people are trying to do sequence to sequences hugging face models. 

If it's not the right place, sorry for that... I just hope it will be useful for someone. 

Here is the template (copy-pasted below): https://gist.github.com/Ierezell/5098ca69e7efcda72a00761612b6b600
```python
"""
Inspired from https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html
Mostly changed variable names and parameters that don't exist in T5.
Added typings
TODO: Maybe some computations are still dynamic and could beneficiate being static
Running the code on the smallest inf ec2 led to 1.2s on the vanilla model / 0.63 on Inf traced one. 
Results are slightly different but correct.
"""
import os
from time import perf_counter
from typing import Any, Optional, cast

import numpy as np
import tensorflow  # type: ignore
import torch
import torch.neuron
from torch.nn import functional as F
from transformers.generation_utils import GenerationMixin
from transformers.modeling_outputs import BaseModelOutput, Seq2SeqLMOutput
from transformers.modeling_utils import PreTrainedModel
from transformers.models.t5.configuration_t5 import T5Config
from transformers.models.t5.modeling_t5 import T5ForConditionalGeneration
from transformers.models.t5.tokenization_t5 import T5Tokenizer

model_id = "mrm8488/t5-base-finetuned-question-generation-ap"
num_texts = 1  # Number of input texts to decode
num_beams = 4  # Number of beams per input text
max_encoder_length = 32  # Maximum input token length
max_decoder_length = 32


def reduce(hidden: torch.Tensor, index: int):
    _, n_length, _ = hidden.shape

    # Create selection mask
    mask = torch.arange(n_length, dtype=torch.float32) == index
    mask = mask.view(1, -1, 1)

    # Broadcast mask
    masked = torch.multiply(hidden, mask)

    # Reduce along 1st dimension
    summed = torch.sum(masked, 1)
    return torch.unsqueeze(summed, 1)


class NeuronEncoder(torch.nn.Module):
    def __init__(self, model: T5ForConditionalGeneration):
        super().__init__()
        self.encoder = model.encoder
        self.encoder.main_input_name = model.main_input_name 

    def forward(self, input_ids: torch.Tensor, attention_mask: torch.Tensor):
        return self.encoder(
            input_ids=input_ids,
            attention_mask=attention_mask,
            return_dict=False,
            output_hidden_states=False,
            output_attentions=False,
        )


class NeuronDecoder(torch.nn.Module):
    def __init__(self, model: T5ForConditionalGeneration, max_length: int):
        super().__init__()
        self.weight = cast(torch.Tensor, model.shared.weight.clone().detach())
        self.decoder = model.decoder
        self.max_length = max_length

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        encoder_outputs: torch.Tensor,
        index: int,
    ):
        # Invoke the decoder
        (hidden,) = self.decoder(
            input_ids=input_ids,
            encoder_hidden_states=encoder_outputs,
            return_dict=False,
            use_cache=False,
        )

        # Reduce decoder outputs to the specified index (current iteration)
        hidden = reduce(hidden, index)

        # Compute final linear layer for token probabilities
        logits = F.linear(hidden, self.weight)
        return logits


class NeuronGeneration(PreTrainedModel, GenerationMixin):
    def trace(
        self,
        model: T5ForConditionalGeneration,
        num_texts: int,
        num_beams: int,
        max_encoder_length: int,
        max_decoder_length: int,
    ) -> None:
        """
        Traces the encoder and decoder modules for use on Neuron.
        This function fixes the network to the given sizes. Once the model has been
        compiled to a given size, the inputs to these networks must always be of
        fixed size.
        Args:
            model (GenerationMixin): The transformer-type generator model to trace
            num_texts (int): The number of input texts to translate at once
            num_beams (int): The number of beams to computer per text
            max_encoder_length (int): The maximum number of encoder tokens
            max_encoder_length (int): The maximum number of decoder tokens
        """
        self.config.max_decoder_length = max_decoder_length

        # Trace the encoder
        inputs = (
            torch.ones((num_texts, max_encoder_length), dtype=torch.long),
            torch.ones((num_texts, max_encoder_length), dtype=torch.long),
        )
        encoder = NeuronEncoder(model)
        self.encoder = cast(NeuronEncoder, torch.neuron.trace(encoder, inputs))

        # Trace the decoder (with expanded inputs)
        batch_size = num_texts * num_beams
        inputs = (
            torch.ones((batch_size, max_decoder_length), dtype=torch.long),
            torch.ones((batch_size, max_encoder_length), dtype=torch.long),
            torch.ones(
                (batch_size, max_encoder_length, model.config.d_model),
                dtype=torch.float,
            ),
            torch.tensor(0),
        )
        decoder = NeuronDecoder(model, max_decoder_length)
        self.decoder = cast(NeuronDecoder, torch.neuron.trace(decoder, inputs))

    # ------------------------------------------------------------------------
    # Encoder/Decoder Invocation
    # ------------------------------------------------------------------------

    def prepare_inputs_for_generation(
        self,
        input_ids: torch.Tensor,
        encoder_outputs: BaseModelOutput,
        attention_mask: Optional[BaseModelOutput] = None,
        **model_kwargs: Any,
    ):
        # Pad the inputs for Neuron
        current_length = input_ids.shape[1]
        pad_size = self.config.max_decoder_length - current_length
        return dict(
            input_ids=F.pad(input_ids, (0, pad_size)),
            attention_mask=attention_mask,
            encoder_outputs=encoder_outputs.last_hidden_state,
            current_length=torch.tensor(current_length - 1),
        )

    def get_encoder(self):
        """Helper to invoke the encoder and wrap the results in the expected structure"""

        def encode(**kwargs:Any):
            input_ids = kwargs["input_ids"]
            attention_mask = kwargs.get("attention_mask", torch.ones_like(input_ids))
            (output,) = self.encoder(input_ids, attention_mask)
            return BaseModelOutput(
                last_hidden_state=output,
            )

        return encode

    def __call__(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        encoder_outputs: BaseModelOutput,
        current_length: int,
        **kwargs: Any,
    ):
        """Helper to invoke the decoder and wrap the results in the expected structure"""
        logits = self.decoder(
            input_ids, attention_mask, encoder_outputs, current_length
        )
        return Seq2SeqLMOutput(logits=logits)

    # ------------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------------

    def save_pretrained(self, directory: str):
        if os.path.isfile(directory):
            print(f"Provided path ({directory}) should be a directory, not a file")
            return
        os.makedirs(directory, exist_ok=True)
        torch.jit.save(self.encoder, os.path.join(directory, "encoder.pt"))
        torch.jit.save(self.decoder, os.path.join(directory, "decoder.pt"))
        self.config.save_pretrained(directory)

    @classmethod
    def from_pretrained(cls, directory: str):
        config = T5Config.from_pretrained(directory)
        obj = cls(config)
        obj.main_input_name = "input_ids"
        obj.encoder = torch.jit.load(os.path.join(directory, "encoder.pt"))
        obj.encoder.main_input_name = "input_ids"
        obj.decoder = torch.jit.load(os.path.join(directory, "decoder.pt"))
        obj.decoder.main_input_name = "decoder_input_ids"
        return obj

    @property
    def device(self):
        return torch.device("cpu")


def infer(model: NeuronGeneration, tokenizer: T5Tokenizer, text: str):
    # Truncate and pad the max length to ensure that the token size is compatible with fixed-sized encoder (Not necessary for pure CPU execution)
    batch = tokenizer(
        text,
        max_length=max_decoder_length,
        truncation=True,
        padding="max_length",
        return_tensors="pt",
    )
    # with torch.inference_mode():
    output = model.generate(
        inputs=batch["input_ids"],
        max_length=max_decoder_length,
        num_beams=num_beams,
        num_return_sequences=num_beams,
    )
    results = [tokenizer.decode(t, skip_special_tokens=True) for t in output]

    print("Texts:")
    for i, summary in enumerate(results):
        print(i + 1, summary)


model_cpu = cast(T5ForConditionalGeneration, T5ForConditionalGeneration.from_pretrained(model_id))
tokenizer_cpu = cast(T5Tokenizer, T5Tokenizer.from_pretrained(model_id))
model_neuron = NeuronGeneration(model_cpu.config)

# UNCOMMENT 1. and 2. to trace and save the model. Then we can just load it for inference.
# # 1. Compile the model
# # Note: This may take a couple of minutes since both the encoder/decoder will be compiled
# model_neuron.trace(
#     model=model_cpu,
#     num_texts=num_texts,
#     num_beams=num_beams,
#     max_encoder_length=max_encoder_length,
#     max_decoder_length=max_decoder_length,
# )

# # # 2. Serialize an artifact
# # # After this call you will have an `encoder.pt`, `decoder.pt` and `config.json` in the neuron_name folder
# model_neuron.save_pretrained("./neuron")
# tokenizer_cpu.save_pretrained("./neuron")

model_neuron = NeuronGeneration.from_pretrained("./neuron")
sample_text = "answer: coffee context: I like have a coffee in the morning."

start = perf_counter()
infer(model_cpu, tokenizer_cpu, sample_text)
print(perf_counter()-start)

# Texts:
# 1 question: What do I like to have in the morning?
# 2 question: What kind of beverage do I like to have in the morning?
# 3 question: What do I like to drink in the morning?
# 4 question: What do I like to have in the mornings?
# Time in seconds: 0.9962826039991342

start = perf_counter()
infer(model_neuron, tokenizer_cpu, sample_text)
print(perf_counter()-start)

# Texts:
# 1 question: What do I like to have in the morning?
# 2 question: What kind of beverage do I like to have in the morning?
# 3 question: What kind of drink do I like to have in the morning?
# 4 question: What do I like to drink in the morning?
# Time in seconds: 0.5620196870004293

``` 

I obtain a gain of ~x2, but I guess it can further be optimized. 

For people trying to adapt other models, the main point is to read the hugging face documentation and to pass the correct parameters to the decoder which can be different from one model to another.
It can be compiled/traced on a non-inferentia machine but will require an inferentia one for inference. 
Requires 3.7 (3.8 is not compatible and I haven't tested 3.6)

Feel free to close this issue or maybe improve/share this T5 template.

**Comment by ogis-uno** [comment]
Hi @ierezell,
Thank you for sharing nice information!
But when I tried your snippet (saved as t5_example.py), I got following error.

```
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
Traceback (most recent call last):
  File "t5_example.py", line 242, in <module>
    max_decoder_length=max_decoder_length,
  File "t5_example.py", line 113, in trace
    encoder = NeuronEncoder(model)
  File "t5_example.py", line 43, in __init__
    self.encoder.main_input_name = model.main_input_name
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'T5ForConditionalGeneration' object has no attribute 'main_input_name'
``` 

I used transformers  4.6.0. Could you tell me what version of transformers you used?

**Comment by ogis-uno** [comment]
#### Update
I switched transformers to 4.23.1, then tracing works fine!
But when loading serialized model and try to generate texts, I got following error...
```
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
Texts:
1 question: What do I like to have in the morning?
2 question: What do I like having in the morning?
3 question: What do I like to drink in the morning?
4 question: What do I like to have in the mornings?
0.5273605799998222
Traceback (most recent call last):
  File "t5_example.py", line 267, in <module>
    infer(model_neuron, tokenizer_cpu, sample_text)
  File "t5_example.py", line 221, in infer
    num_return_sequences=num_beams,
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/generation_utils.py", line 1466, in generate
    **model_kwargs,
  File "/opt/conda/lib/python3.7/site-packages/transformers/generation_utils.py", line 2304, in beam_search
    output_hidden_states=output_hidden_states,
  File "t5_example.py", line 174, in __call__
    input_ids, attention_mask, encoder_outputs, current_length
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: forward() Expected a value of type 'Tensor' for argument 'argument_2' but instead found type 'NoneType'.
Position: 2
Value: None
Declaration: forward(__torch__.torch_neuron.runtime.___torch_mangle_1078.AwsNeuronGraphModule self, Tensor argument_1, Tensor argument_2, Tensorargument_3, Tensor argument_4) -> (Tensor)
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

**Comment by ogis-uno** [comment]
with 4.20.1, plus slight modification to `NeuronGeneration.__call__()` as follows,
* I think the value of attention_mask doesn't matter because `NeuronDecoder.forward()`  ignoring that. (But I'm wondering why...)

```
    def __call__(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        encoder_outputs: BaseModelOutput,
        current_length: int,
        **kwargs: Any,
    ):
        if not attention_mask :                        # FIXED
          attention_mask = torch.zeros_like(input_ids) # FIXED

        """Helper to invoke the decoder and wrap the results in the expected structure"""
        logits = self.decoder(
            input_ids, attention_mask, encoder_outputs, current_length
        )
        return Seq2SeqLMOutput(logits=logits)
```

it seems to work.

```
# python t5_example.py
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
Texts:
1 question: What do I like to have in the morning?
2 question: What do I like having in the morning?
3 question: What do I like to drink in the morning?
4 question: What do I like to have in the mornings?
0.5293127069999173
Texts:
1 question: What do I like to have in the morning?
2 question: What kind of drink do I like to have in the morning?
3 question: What do I like having in the morning?
4 question: What do I like in the morning?
0.5487863500002277
```
