### ISSUE TITLE
Compilation failed for Convnext pytorch model

### ISSUE THREAD

**Issue by dingusagar** [aws/aws-neuron-sdk#449]
The neuron-cc compilation fails for convnext model taken from https://github.com/rwightman/pytorch-image-models

```py
import timm
from PIL import Image
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform
import torch
import torch_neuron
import requests
from io import BytesIO

url = "https://www.slazzer.com/static/images/home-page/banner-orignal-image.jpg"
response = requests.get(url)
img = Image.open(BytesIO(response.content))


MODEL_NAME = "convnext_base_in22k"
model = timm.create_model(MODEL_NAME, pretrained=True, num_classes=0)
config = resolve_data_config({}, model=model)
transform_func = create_transform(**config)
preprocessed_img = transform_func(img.convert("RGB")).unsqueeze(0)

print('Preprocessed input tensor shape : ', preprocessed_img.shape)

model_neuron = torch_neuron.trace(model, example_inputs=(preprocessed_img,), compiler_workdir="neuron-workspace-2")

model_neuron.save("convnext_base_neuron.pt")
```

logs
```
INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 598, fused = 598, percent fused = 100.0%
INFO:Neuron:Compiling function _NeuronGraph$1180 with neuron-cc; log file is at /media/dingusagar/Data/ecommerce_ml_pocs/neuron-workspace-2/0/graph_def.neuron-cc.log
INFO:Neuron:Compiling with command line: '/media/dingusagar/Data/python-envs/neuron-env/bin/neuron-cc compile /media/dingusagar/Data/ecommerce_ml_pocs/neuron-workspace-2/0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /media/dingusagar/Data/ecommerce_ml_pocs/neuron-workspace-2/0/graph_def.neff --io-config {"inputs": {"0:0": [[1, 3, 224, 224], "float32"]}, "outputs": ["Reshape_36:0"]} --verbose 35'
INFO:Neuron:Compile command returned: -9
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$1180; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/media/dingusagar/Data/python-envs/neuron-env/bin/neuron-cc compile /media/dingusagar/Data/ecommerce_ml_pocs/neuron-workspace-2/0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /media/dingusagar/Data/ecommerce_ml_pocs/neuron-workspace-2/0/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 224, 224], "float32"]}, "outputs": ["Reshape_36:0"]}' --verbose 35
Traceback (most recent call last):
  File "/media/dingusagar/Data/python-envs/neuron-env/lib/python3.7/site-packages/torch_neuron/convert.py", line 346, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/media/dingusagar/Data/python-envs/neuron-env/lib/python3.7/site-packages/torch_neuron/decorators.py", line 196, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/media/dingusagar/Data/python-envs/neuron-env/bin/neuron-cc compile /media/dingusagar/Data/ecommerce_ml_pocs/neuron-workspace-2/0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /media/dingusagar/Data/ecommerce_ml_pocs/neuron-workspace-2/0/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 224, 224], "float32"]}, "outputs": ["Reshape_36:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 598, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::_convolution: 40 [supported]
INFO:Neuron: => aten::adaptive_avg_pool2d: 1 [supported]
INFO:Neuron: => aten::add: 108 [supported]
INFO:Neuron: => aten::dropout: 73 [supported]
INFO:Neuron: => aten::flatten: 1 [supported]
INFO:Neuron: => aten::gelu: 36 [supported]
INFO:Neuron: => aten::layer_norm: 41 [supported]
INFO:Neuron: => aten::matmul: 72 [supported]
INFO:Neuron: => aten::mul: 36 [supported]
INFO:Neuron: => aten::permute: 82 [supported]
INFO:Neuron: => aten::reshape: 36 [supported]
INFO:Neuron: => aten::t: 72 [supported]
Traceback (most recent call last):
  File "/media/dingusagar/Data/ecommerce_ml_pocs/model_optimisation_scripts/neuron_timm_model.py", line 24, in <module>
    model_neuron = torch_neuron.trace(model, example_inputs=(preprocessed_img,), compiler_workdir="neuron-workspace-2")
  File "/media/dingusagar/Data/python-envs/neuron-env/lib/python3.7/site-packages/torch_neuron/convert.py", line 124, in trace
    cu.stats_post_compiler(neuron_graph)
  File "/media/dingusagar/Data/python-envs/neuron-env/lib/python3.7/site-packages/torch_neuron/convert.py", line 457, in stats_post_compiler
    "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!

```

**Comment by dingusagar** [comment]
Thanks @jluntamazon. will try it on a larger instance.
