### ISSUE TITLE
Running neuron compiled models in CPU. 

### ISSUE THREAD

**Issue by dingusagar** [aws/aws-neuron-sdk#458]
Usecase: I needed to setup the inference servers in multiple environments like dev, production. Was thinking to use the inferentia instance for production environment and use a normal cpu instance for dev environment to save costs. For this I was expecting the inference code of the neuron model to work both in cpu instance and inferentia instance. 

In one of the older versions of torch-neuron, I was able to run the neuron model in my local CPU machine. 
 
```
[E session.cpp:41] The Neuron Runtime GRPC server at address unix:/run/neuron.sock is unavailable. Is neuron-rtd running? Is socket /run/neuron.sock writable?
[W neuron_op_v2.cpp:52] Warning: Neuron runtime could not be initialized. Model was not sent to NeuronCore (function load)
[W neuron_op_v2.cpp:88] Warning: Model was compiled with a newer version of torch-neuron than the current runtime (function operator())
[W neuron_op_v2.cpp:52] Warning: Neuron runtime could not be initialized. Model was not sent to NeuronCore (function load)
[W neuron_op_v2.cpp:88] Warning: Model was compiled with a newer version of torch-neuron than the current runtime (function operator())
INFO:     Started server process [81310]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```
I was able to run the model in CPU. there were also logs mentioning its falling back to cpu since neuron cores were not detected. 

But when I upgraded to the latest torch-neuron version, this fallback to CPU stopped working. I am no longer able to run the same inference code in CPU. 
```
/media/dingusagar/Data/python-envs/neuron-env/bin/python3.7 /media/dingusagar/Data/ecommerce_ml_pocs/model-inference-engine/all-MiniLM-L12-V2-neuron/main.py 
2022-Aug-02 17:56:53.0257 84988:84988 ERROR   NRT:nrt_init                                Unable to determine Neuron Driver version. Please check aws-neuron-dkms package is installed.
Traceback (most recent call last):
  File "/media/dingusagar/Data/ecommerce_ml_pocs/model-inference-engine/all-MiniLM-L12-V2-neuron/main.py", line 20, in <module>
    model = torch.jit.load(NEURON_MODEL_PATH)
  File "/media/dingusagar/Data/python-envs/neuron-env/lib/python3.7/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/media/dingusagar/Data/python-envs/neuron-env/lib/python3.7/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged
to your system logs. See the Neuron Runtime's troubleshooting guide for help on this
topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/

```

**Comment by dingusagar** [comment]
This is the version which is working `torch-neuron==1.8.1.1.5.12.0`

**Comment by aws-stdun** [comment]
Hi dingusagar, 

Some of our old version of neuron compiled models did return a value when run on CPU, but this was a bug.
In your situation (CPU dev env. vs prod), we recommend storing two versions of your model. For CPU, you can
serialize your model without Neuron using `torch.jit.trace`, and then load that model in your dev environment.

**Comment by dingusagar** [comment]
Thanks a lot for the reply @aws-stdun ,  will go with 2 separate models as you recommended.
