### ISSUE TITLE
Runtime Error: torch.neuron.trace model 

### ISSUE THREAD

**Issue by di0002ya** [aws/aws-neuron-sdk#470]
Hi team, I tried to compiled model by using pytorch neuron and deployed to inferentia. 

I firstly run: 
`torch.neuron.analyze_model(det_model, inputs)`

Output shows all operations are supported. 

```
INFO:Neuron:100.00% of all operations (including primitives) (1217 of 1217) are supported
INFO:Neuron:100.00% of arithmetic operations (160 of 160) are supported
```

However, when I tried 
`model_neuron = torch.neuron.trace(det_model,  inputs ) `

I got runtime error. May I know how to solve it? Thanks in advance! 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_2684/3971781750.py in <module>
      1 # that that is optimized for the Inferentia hardware
----> 2 model_neuron = torch.neuron.trace(det_model,  inputs )
      3 # The output of the compilation step will report the percentage of operators that
      4 # are compiled to Neuron, for example:
      5 #

~/.pyenv/versions/3.7.13/envs/neuron/lib/python3.7/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    166     with skip_inference_context() as s:
    167         neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 168     cu.stats_post_compiler(neuron_graph)
    169 
    170     # Wrap the compiled version of the model in a script module. Note that this is

~/.pyenv/versions/3.7.13/envs/neuron/lib/python3.7/site-packages/torch_neuron/convert.py in stats_post_compiler(self, neuron_graph)
    498         if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
    499             raise RuntimeError(
--> 500                 "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    501 
    502         if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

```
ERROR:Neuron:neuron-cc failed with the following command line call:
/workspace/.pyenv/versions/3.7.13/envs/neuron/bin/neuron-cc compile /tmp/tmpx7n7uwpf/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpx7n7uwpf/graph_def.neff --io-config '{"inputs": {}, "outputs": []}' --verbose 35
Traceback (most recent call last):
  File "/workspace/.pyenv/versions/3.7.13/envs/neuron/lib/python3.7/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/workspace/.pyenv/versions/3.7.13/envs/neuron/lib/python3.7/site-packages/torch_neuron/decorators.py", line 221, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/workspace/.pyenv/versions/3.7.13/envs/neuron/bin/neuron-cc compile /tmp/tmpx7n7uwpf/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpx7n7uwpf/graph_def.neff --io-config '{"inputs": {}, "outputs": []}' --verbose 35
```

**Comment by aws-taylor** [comment]
Hello @di0002ya,

 The issue you are running into is related to the empty `--io-config '{"inputs": {}, "outputs": []}'`. Are you able to share the commands necessary to reproduce this issue? 
 
 -Taylor

**Comment by di0002ya** [comment]
Hi @aws-taylor , thanks for your help! I tried to re-organize my model wrapper yesterday.

**Comment by di0002ya** [comment]
After running `model_neuron = torch.neuron.trace(det_model, example_inputs=[inputs], strict = False)`. it shows `WARNING:Neuron:torch.neuron.trace was unable to compile > 50% of the operators in the compiled model!
WARNING:Neuron:Please review the torch.neuron.analyze_model output and if you believe you are seeing a failure
WARNING:Neuron:Lodge an issue on https://github.com/aws/aws-neuron-sdk/issues if you believe the model is not compiling as expected` without breaking the process. 

However, when I tried to run inference on neuron model using following command: 
```
model_neuron.eval()
model_neuron(inputs)
```

Log was shown below: 
2022-Aug-18 08:22:45.0374  5279:5279  ERROR   NRT:nrt_init                                Unable to read compatible Driver version.
2022-Aug-18 08:22:45.0374  5279:5279  ERROR   NRT:nrt_init                                Please check /dev/neuron# is accessible. If you're using containers, please ensure Neuron Devices are passed to the container by specifying `--device /dev/neuron#`.
```

**Comment by aws-taylor** [comment]
Hello @di0002ya ,

  Are you able to share the associated model configuration and checkpoint files? We have a candidate fix, but without a reproduction it's difficult to test. Specifically these files:
  
  ```
  det_ckpt = "checkpoints/dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth"
  recog_ckpt = "checkpoints/textrec/abinet_academic-f718abf6.pth"
  det_config = "dbr18config.py"
  recog_config = "abinet_recog_config.py"
  ```
