### ISSUE TITLE
undefined symbol on `c5.4xlarge`

### ISSUE THREAD

**Issue by yugoren** [aws/aws-neuron-sdk#73]
I was following BERT example on a `c5.4xlarge` instance when I came across the following error:
```python
ImportError: /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/neuron/_whitelist_partition_swig.so: undefined symbol: _ZN10tensorflow10FileSystem20RecursivelyCreateDirERKSs
```
when I ran `bert_model.py`. Here's a MWE without BERT example:
<pre>
(aws_neuron_tensorflow_p36) ubuntu@ip-172-31-95-164:~/aws-neuron-sdk/src/examples/tensorflow/bert_demo$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> <b>from tensorflow.neuron import fuse</b>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/_api/v1/neuron/__init__.py", line 10, in <module>
    from tensorflow._api.v1.neuron import graph_util
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/_api/v1/neuron/__init__.py", line 10, in <module>
    from tensorflow._api.v1.neuron import graph_util
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/_api/v1/neuron/graph_util/__init__.py", line 10, in <module>
    from tensorflow.python.neuron.python.graph_util import inference_graph_from_session
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/neuron/python/graph_util.py", line 42, in <module>
    from tensorflow.python.neuron.whitelist_partition_swig import WhitelistPartition
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/neuron/whitelist_partition_swig.py", line 28, in <module>
    _whitelist_partition_swig = swig_import_helper()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/neuron/whitelist_partition_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_whitelist_partition_swig', fp, pathname, description)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/neuron/_whitelist_partition_swig.so: undefined symbol: _ZN10tensorflow10FileSystem20RecursivelyCreateDirERKSs
</pre>
Same missing symbol error is also present for `from  tensorflow import neuron as tfn`. I also found out that this works without a problem on `inf1.6xlarge`.

**Comment by awsrjh** [comment]
Hello yugoren

let us have a look and get back to you.

**Comment by spring01** [comment]
This issue is caused by a mismatch between installed tensorflow and the needed tensorflow-neuron packages, such as with tensorflow-gpu or tensorflow==2.0.
 
The solution is to reinstall tensorflow-neuron with one of two methods:
 
Using pip:
 
```bash
pip install tensorflow-neuron --force
```
 
Or by using conda:
 
```bash
conda install tensorflow-neuron --force
```
